### ISSUE TITLE
FedoraRemixforWSL exposes wrong OS version: cat /etc/osrelease VERSION="33" 

### ISSUE THREAD

**Issue by PavelSosin-320** [WhitewaterFoundry/Fedora-Remix-for-WSL#109]
**Describe the bug**
FedoraRemixForWSL expose wrong OS release: version=33.

**To Reproduce**
1. Install Fedors33Remix from Microsoft store
2. Upgrade to FedorsRemixWSL Beta following Guideline [Upgrade Fedora Remix for WSL to 34 (Beta)](https://www.whitewaterfoundry.com/blog/2019/11/3/upgrade-fedora-remix-for-wsl-to-31-2a7z8-njsec-fl7bd) 
3. /etc/os-release
NAME="Fedora Remix for WSL"
VERSION="33"
ID=fedoraremixforwsl
ID_LIKE=fedora
VERSION_ID=33
PLATFORM_ID="platform:f33"
PRETTY_NAME="Fedora Remix for WSL"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:33"
HOME_URL="https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL"
SUPPORT_URL="https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL"
BUG_REPORT_URL="https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL/issues"
PRIVACY_POLICY_URL="https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL/blob/master/PRIVACY.md"
**FEDORA_REMIX_VERSION=33.2.1**

**Expected behavior**
FEDORA_REMIX_VERSION=34 is shown

**Screenshots**

**Additional context**
Systemd-genie is used to run the distro with systemd.
hostnamectl
   Static hostname: MSI-wsl
         Icon name: computer-container
           Chassis: container
        Machine ID: 65f666557bef4dbcb6884dd5c7f2cd23
           Boot ID: c20ac4fe79e4427491ea200d8e4cb2c1
    Virtualization: wsl
  Operating System: Fedora Remix for WSL
       CPE OS Name: cpe:/o:fedoraproject:fedora:33
            Kernel: Linux 5.10.16.3-microsoft-standard-WSL2
      Architecture: x86-64

**Basic Troubleshooting Checklist**

[X] I have searched Google for the error message.
[X ] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[ ] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[ ] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
[ ] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
[ ] I have disabled and re-enabled WSL in Windows Features.
[ ] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

hostnamectl
   Static hostname: MSI-wsl
         Icon name: computer-container
           Chassis: container
        Machine ID: 65f666557bef4dbcb6884dd5c7f2cd23
           Boot ID: c20ac4fe79e4427491ea200d8e4cb2c1
    Virtualization: wsl
  Operating System: Fedora Remix for WSL
       CPE OS Name: cpe:/o:fedoraproject:fedora:33
            Kernel: Linux 5.10.16.3-microsoft-standard-WSL2
      Architecture: x86-64

**WLinux Version**

Insert here:

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.21364 N/A Build 21364

dnf search kata-containers
Last metadata expiration check: 0:17:30 ago on Sat Apr 24 14:19:52 2021.
No matches found. <-- 1st released for Fedora34!
and 
hostnamectl status
   Static hostname: MSI-wsl
         Icon name: computer-container
           Chassis: container
        Machine ID: 65f666557bef4dbcb6884dd5c7f2cd23
           Boot ID: c20ac4fe79e4427491ea200d8e4cb2c1
    Virtualization: wsl
  Operating System: Fedora Remix for WSL
       CPE OS Name: cpe:/o:fedoraproject:fedora:33
            Kernel: Linux 5.10.16.3-microsoft-standard-WSL2
      Architecture: x86-64

I'm afraid that all system utilities in systemd-based distros expect xxxCtl interfaces instead lsb_release that is missed.

**Comment by crramirez** [comment]
Good finding. Thank you for reporting.

**Comment by crramirez** [comment]
Hello @PavelSosin-320,

The issue is fixed. To fix your current installation run:

`sudo curl -L -f "https://raw.githubusercontent.com/WhitewaterFoundry/fedora-remix-rootfs-build/master/linux_files/os-release-34" -o /etc/os-release`

Regards,
Carlos

**Comment by PavelSosin-320** [comment]
SOLVED
Thanks, It works! Cross-check:
1.  hostnamectl
 Virtualization: wsl
  _Operating System: Fedora Remix for WSL
       CPE OS Name: cpe:/o:fedoraproject:fedora:34
            Kernel: Linux 5.10.16.3-microsoft-standard-WSL2
      Architecture: x86-64_

2. Kata-containers has been installed
kata-runtime --version
_kata-runtime  : 1.12.1
   commit   : <<unknown>>
   OCI specs: 1.0.1-dev___
3. Podman version recognition
_podman info
  distribution:
    distribution: fedoraremixforwsl
    version: "34_"
