### ISSUE TITLE
Ping-Socket Error on User (Wlinux Bug : #226) 

### ISSUE THREAD

**Issue by thunderbirdtr** [WhitewaterFoundry/Fedora-Remix-for-WSL#12]
**Describe the bug**
It was the same "bug" happened on Wlinux  as well --> 
https://github.com/WhitewaterFoundry/WLinux/issues/226

It just started after fresh install 

![image](https://user-images.githubusercontent.com/1688848/51165553-a94a2f00-18b1-11e9-949c-aa4861032a0a.png)

**Expected behavior**
It should be ping as user too. 

**Screenshots**

![image](https://user-images.githubusercontent.com/1688848/51165571-b23b0080-18b1-11e9-942f-8f59ed7fa2d9.png)

**Basic Troubleshooting Checklist**

[x] I have searched Google for the error message.
[x ] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[-] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[x] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
[-] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
[-] I have disabled and re-enabled WSL in Windows Features.
[-] I have run Windows 10 updates and restarted.

Fedora Remix for WSL - Version :  1.0.25.0
**Windows Build**

OS Name:                   Microsoft Windows 10 Pro Insider Preview
OS Version:                10.0.18312 N/A Build 18312

**Comment by grufwub** [comment]
The issue seems to be /bin/ping not having the required setuid bit, as ping requires root for creating a raw network socket. Running "sudo chmod u+s /bin/ping" fixes this issue. Why this is situation here? I'm not sure, but I'm going to do some digging.

**Comment by crramirez** [comment]
Fixed with the latest release

**Comment by barnscott** [comment]
Just for reference, I just encountered this same issue. Had not had issue since I installed FedoraRemix on this PC in Oct 2019. 
I updated my PC to 2004, upgraded to release 32, and issue began. Not sure exactly what caused it, but the same resolution fixed it: sudo chmod u+s /bin/ping

**Comment by crramirez** [comment]
Thank you for report it. Maybe the upgrade to Fedora 32 reset the bit. We will take this into account for the image generation of Fedora 32, also for the instructions in the blog.

Be sure that for Fedora 32 you are in WSL2 due to an issue with WSL1

**Comment by barnscott** [comment]
Noted. And yes, as part of 2004 upgrade i did also move to wsl2
