### ISSUE TITLE
Dnf update on 34.5.6.0 fails with ‘Empty reply from server’ when using a proxy

### ISSUE THREAD

**Issue by Egwor** [WhitewaterFoundry/Fedora-Remix-for-WSL#127]
**Describe the bug**
On a brand new install, `dnf update` doesn’t run successfully.

**To Reproduce**
1. Using Windows 10 and WSL1 install 34.5.6.0 Final from the releases
2. Create a user
3. Login
4. Edit the /etc/dnf/dnf.conf and add proxy details 
```
proxy=http://proxy:8080
proxy_username=blah
proxy_password=blah
```
5. Run `sudo dnf update`
6. See errors `Curl error (56): Failure when receiving data from the peer for https://download.copr.fedorainfracloud.org/results/wslutilities/wslu/fedora-34-x86_64/repodata/repomd.xml [Empty reply from server]`

<img width="1366" alt="Dnf update" src="https://user-images.githubusercontent.com/238535/125269445-9c7ee880-e300-11eb-97ae-0207e5f4f3e1.png">

**Expected behavior**
Expect dnf update to run and connect ok

**Additional context**
I am running behind a proxy, so there’s a small chance that this might be proxy blocking but I’ve tried to eliminate that as an issue.

Checking the os-release, since that seems to have been an issue in the past:
`cat /etc/os-release | grey NAME`
`NAME=“Fedora Remix for WSL”`

**Basic Troubleshooting Checklist**

[x] I have searched Google for the error message.
[x] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[x] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[x] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
[x] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
_Reinstalled the Remix_
[x] I have disabled and re-enabled WSL in Windows Features.
[x] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?
* I’ve reinstalled the remix from scratch
* curl http://www.google.com works and https://www.google.com
* Breaking the proxy settings to see that I get a proxy error (e.g. authentication) to check that this isn’t the issue

**WLinux Version**

Find: Settings->Apps->Apps & features->WLinux->Advanced Options->Version.
I don’t see WLinux. I do see Fedora Remix for WSL is 34.5.6.0.

**Windows Build**
```
OS Name: Microsoft Windows 10 Enterprise
OS Version:  10.0.18363 N/A Build 18363

```

**Comment by crramirez** [comment]
Hello @Egwor,

Looks like it is an internet connection problem. Check if you have a VPN enabled.

Why did you edit  /etc/dnf/dnf.conf and added proxy details. Have you tried without proxy?

Regards,
Carlos

**Comment by Egwor** [comment]
Hi
I have a VPN enabled, and then once the VPN is initiated any connections to the internet are via proxy. I’ve tried without proxy, and after a while it times out. The issues I’m seeing tend to be much quicker responses though,

**Comment by crramirez** [comment]
Ok, give me more info. How the proxy is configured in Windows? 

Could you test for example with curl or wget after setting the environment variable?

export http_proxy="http://PROXY=USERNAME=HERE:PROXY=PASSWORD=HERE@URL:PORT"
