### ISSUE TITLE
after upgrade to 34 package management is not working properly

### ISSUE THREAD

**Issue by vobo70** [WhitewaterFoundry/Fedora-Remix-for-WSL#130]
**Describe the bug**
After do update from 32 to 34 based on this blog:
https://www.whitewaterfoundry.com/blog/2019/11/3/upgrade-fedora-remix-for-wsl-to-31-2a7z8-njsec-fl7bd
yum upgrage gives me errors:

warning: Found bdb_ro Packages database while attempting sqlite backend: using bdb_ro backend.
warning: Found bdb_ro Packages database while attempting sqlite backend: using bdb_ro backend.
warning: Found bdb_ro Packages database while attempting sqlite backend: using bdb_ro backend.
warning: Found bdb_ro Packages database while attempting sqlite backend: using bdb_ro backend.
warning: Found bdb_ro Packages database while attempting sqlite backend: using bdb_ro backend.
warning: Found bdb_ro Packages database while attempting sqlite backend: using bdb_ro backend.
warning: Found bdb_ro Packages database while attempting sqlite backend: using bdb_ro backend.
warning: Found bdb_ro Packages database while attempting sqlite backend: using bdb_ro backend.
warning: Found bdb_ro Packages database while attempting sqlite backend: using bdb_ro backend.
warning: Found bdb_ro Packages database while attempting sqlite backend: using bdb_ro backend.
warning: Found bdb_ro Packages database while attempting sqlite backend: using bdb_ro backend.
Running transaction check
warning: Found bdb_ro Packages database while attempting sqlite backend: using bdb_ro backend.
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
RPM: warning: Found bdb_ro Packages database while attempting sqlite backend: using bdb_ro backend.
RPM: error: cannot open Packages index using bdb_ro - Operation not permitted (1)
RPM: error: cannot open Packages database in /var/lib/rpm
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Could not run transaction.

**To Reproduce**
sudo yum update

**Expected behavior**
yum update should work

**Basic Troubleshooting Checklist**

[ ] I have searched Google for the error message.
[ ] I have tried sudo yum clean packages

**WLinux Version**

Fedora Remix for WSL
34.5.6.0

**Windows Build**
21H1 19043.1110

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19043 N/A Build 19043
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              Dell Inc. 1.16.3, 05.03.2021

**Comment by crramirez** [comment]
Hello @vobo70 

Run this: `upgrade.sh` inside there is a fix for dnf's most recent version.

I will update the blog post.

Thanks for pointing out

**Comment by vobo70** [comment]
after ./upgrade still no luck

`root@NVIGBHNMJR2 maciek]# ./upgrade.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3310  100  3310    0     0  13187      0 --:--:-- --:--:-- --:--:-- 13134
/usr/local/bin/upgrade.sh: OK
warning: Found bdb_ro Packages database while attempting sqlite backend: using bdb_ro backend.
warning: Found bdb_ro Packages database while attempting sqlite backend: using bdb_ro backend.
Copr repo for wslu owned by wslutilities                                                5.7 kB/s | 3.3 kB     00:00
Fedora 34 - x86_64                                                                      127 kB/s |  26 kB     00:00
Fedora 34 openh264 (From Cisco) - x86_64                                                2.3 kB/s | 989  B     00:00
Fedora Modular 34 - x86_64                                                              216 kB/s |  25 kB     00:00
Fedora 34 - x86_64 - Updates                                                             41 kB/s |  24 kB     00:00
Fedora Modular 34 - x86_64 - Updates                                                     40 kB/s |  24 kB     00:00
Dependencies resolved.
======================================================================================================================== Package                                       Architecture    Version                           Repository        Size
========================================================================================================================Upgrading:
 NetworkManager                                x86_64          1:1.30.6-1.fc34                   updates          2.3 M
 NetworkManager-libnm                          x86_64          1:1.30.6-1.fc34                   updates          1.6 M
 alsa-lib                                      x86_64          1.2.5.1-1.fc34                    updates          484 k
 audit                                         x86_64          3.0.3-1.fc34                      updates          249 k
 audit-libs                                    x86_64          3.0.3-1.fc34                      updates          114 k
 ca-certificates                               noarch          2021.2.50-1.0.fc34                updates          350 k
 coreutils                                     x86_64          8.32-30.fc34                      updates          1.1 M
 coreutils-common                              x86_64          8.32-30.fc34                      updates          2.0 M
 cpp                                           x86_64          11.2.1-1.fc34                     updates           10 M
 cryptsetup-libs                               x86_64          2.3.6-1.fc34                      updates          474 k
 curl                                          x86_64          7.76.1-7.fc34                     updates          297 k
 dbus-broker                                   x86_64          29-2.fc34                         updates          172 k
 dhcp-client                                   x86_64          12:4.4.2-11.b1.fc34               updates          795 k
 dhcp-common                                   noarch          12:4.4.2-11.b1.fc34               updates          129 k
 distribution-gpg-keys                         noarch          1.55-1.fc34                       updates          338 k
 dnf                                           noarch          4.8.0-1.fc34                      updates          450 k
 dnf-data                                      noarch          4.8.0-1.fc34                      updates           47 k
 dnf-plugins-core                              noarch          4.0.22-1.fc34                     updates           36 k
 dracut                                        x86_64          055-3.fc34                        updates          347 k
 elfutils                                      x86_64          0.185-2.fc34                      updates          517 k
 elfutils-debuginfod-client                    x86_64          0.185-2.fc34                      updates           36 k
 elfutils-default-yama-scope                   noarch          0.185-2.fc34                      updates           18 k
 elfutils-libelf                               x86_64          0.185-2.fc34                      updates          192 k
 elfutils-libs                                 x86_64          0.185-2.fc34                      updates          263 k
 emacs-filesystem                              noarch          1:27.2-4.fc34                     updates          8.5 k
 expat                                         x86_64          2.4.1-1.fc34                      updates          110 k
 file                                          x86_64          5.39-6.fc34                       updates           50 k
 file-libs                                     x86_64          5.39-6.fc34                       updates          588 k
 fontconfig                                    x86_64          2.13.94-2.fc34                    updates          273 k
 gdb-minimal                                   x86_64          10.2-3.fc34                       updates          3.6 M
 generic-release                               noarch          34-0.3                            updates          7.8 k
 generic-release-common                        noarch          34-0.3                            updates           13 k
 glibc                                         x86_64          2.33-20.fc34                      updates          3.4 M
 glibc-common                                  x86_64          2.33-20.fc34                      updates          1.5 M
 glibc-doc                                     noarch          2.33-20.fc34                      updates          995 k
 glibc-langpack-en                             x86_64          2.33-20.fc34                      updates          563 k
 glibc-minimal-langpack                        x86_64          2.33-20.fc34                      updates           11 k
 gnutls                                        x86_64          3.7.2-1.fc34                      updates          1.0 M
 grub2-common                                  noarch          1:2.06-2.fc34                     updates          924 k
 grub2-tools                                   x86_64          1:2.06-2.fc34                     updates          1.8 M
 grub2-tools-minimal                           x86_64          1:2.06-2.fc34                     updates          604 k
 gstreamer1                                    x86_64          1.19.1-2.1.18.4.fc34              updates          1.4 M
 gtk-update-icon-cache                         x86_64          3.24.30-1.fc34                    updates           35 k
 gtk3                                          x86_64          3.24.30-1.fc34                    updates          4.8 M
 ipcalc                                        x86_64          1.0.1-1.fc34                      updates           41 k
 jasper-libs                                   x86_64          2.0.32-1.fc34                     updates          151 k
 kmod                                          x86_64          29-2.fc34                         updates          114 k
 kmod-libs                                     x86_64          29-2.fc34                         updates           63 k
 krb5-libs                                     x86_64          1.19.1-14.fc34                    updates          716 k
 libX11                                        x86_64          1.7.2-3.fc34                      updates          646 k
 libX11-common                                 noarch          1.7.2-3.fc34                      updates          152 k
 libX11-xcb                                    x86_64          1.7.2-3.fc34                      updates           11 k
 libXfixes                                     x86_64          6.0.0-1.fc34                      updates           19 k
 libaom                                        x86_64          3.1.1-1.fc34                      updates          1.6 M
 libavif                                       x86_64          0.9.0-2.fc34                      updates           64 k
 libcomps                                      x86_64          0.1.17-1.fc34                     updates           77 k
 libcurl                                       x86_64          7.76.1-7.fc34                     updates          284 k
 libdav1d                                      x86_64          0.9.0-1.fc34                      updates          431 k
 libdnf                                        x86_64          0.63.1-1.fc34                     updates          643 k
 libeconf                                      x86_64          0.4.0-1.fc34                      updates           27 k
 libedit                                       x86_64          3.1-38.20210714cvs.fc34           updates          104 k
 libepoxy                                      x86_64          1.5.8-1.fc34                      updates          245 k
 libgcc                                        x86_64          11.2.1-1.fc34                     updates          107 k
 libgcrypt                                     x86_64          1.9.3-3.fc34                      updates          507 k
 libgomp                                       x86_64          11.2.1-1.fc34                     updates          279 k
 libgs                                         x86_64          9.53.3-6.fc34                     updates          3.1 M
 libgusb                                       x86_64          0.3.7-1.fc34                      updates           49 k
 libibverbs                                    x86_64          36.0-1.fc34                       updates          354 k
 libidn2                                       x86_64          2.3.2-1.fc34                      updates          103 k
 libmodulemd                                   x86_64          2.13.0-1.fc34                     updates          231 k
 libpcap                                       x86_64          14:1.10.1-1.fc34                  updates          171 k
 librepo                                       x86_64          1.14.1-1.fc34                     updates           95 k
 libreport-filesystem                          noarch          2.15.2-2.fc34                     updates           16 k
 librsvg2                                      x86_64          2.50.6-1.fc34                     updates          3.4 M
 libstdc++                                     x86_64          11.2.1-1.fc34                     updates          696 k
 libuser                                       x86_64          0.63-4.fc34                       updates          382 k
 libvmaf                                       x86_64          2.1.1-1.fc34                      updates          171 k
 libxcrypt                                     x86_64          4.4.23-1.fc34                     updates          116 k
 libxcrypt-compat                              x86_64          4.4.23-1.fc34                     updates           89 k
 libxml2                                       x86_64          2.9.12-4.fc34                     updates          737 k
 mkpasswd                                      x86_64          5.5.10-1.fc34                     updates           41 k
 mpfr                                          x86_64          4.1.0-7.fc34                      updates          326 k
 netpbm                                        x86_64          10.95.00-1.fc34                   updates          185 k
 nettle                                        x86_64          3.7.3-1.fc34                      updates          391 k
 openjpeg2                                     x86_64          2.4.0-3.fc34                      updates          163 k
 openldap                                      x86_64          2.4.57-5.fc34                     updates          256 k
 openssh                                       x86_64          8.6p1-3.fc34                      updates          438 k
 openssh-clients                               x86_64          8.6p1-3.fc34                      updates          678 k
 openssh-server                                x86_64          8.6p1-3.fc34                      updates          451 k
 pam                                           x86_64          1.5.1-6.fc34                      updates          544 k
 pango                                         x86_64          1.48.7-1.fc34                     updates          299 k
 polkit-libs                                   x86_64          0.117-3.fc34.1                    updates           65 k
 python-setuptools-wheel                       noarch          53.0.0-2.fc34                     updates          470 k
 python-srpm-macros                            noarch          3.9-38.fc34                       updates           20 k
 python-unversioned-command                    noarch          3.9.6-2.fc34                      updates           12 k
 python3                                       x86_64          3.9.6-2.fc34                      updates           28 k
 python3-dbus                                  x86_64          1.2.18-1.fc34                     updates          132 k
 python3-dnf                                   noarch          4.8.0-1.fc34                      updates          415 k
 python3-dnf-plugin-system-upgrade             noarch          4.0.15-1.fc34                     updates           31 k
 python3-dnf-plugins-core                      noarch          4.0.22-1.fc34                     updates          210 k
 python3-dnf-plugins-extras-common             noarch          4.0.15-1.fc34                     updates           61 k
 python3-hawkey                                x86_64          0.63.1-1.fc34                     updates          114 k
 python3-libcomps                              x86_64          0.1.17-1.fc34                     updates           48 k
 python3-libdnf                                x86_64          0.63.1-1.fc34                     updates          783 k
 python3-libs                                  x86_64          3.9.6-2.fc34                      updates          7.3 M
 python3-setuptools                            noarch          53.0.0-2.fc34                     updates          840 k
 rav1e-libs                                    x86_64          0.4.1-2.fc34                      updates          774 k
 redhat-rpm-config                             noarch          183-1.fc34                        updates           66 k
 rust-srpm-macros                              noarch          18-1.fc34                         updates          9.2 k
 svt-av1-libs                                  x86_64          0.8.7-1.fc34                      updates          4.5 M
 systemd                                       x86_64          248.6-1.fc34                      updates          4.4 M
 systemd-libs                                  x86_64          248.6-1.fc34                      updates          586 k
 systemd-networkd                              x86_64          248.6-1.fc34                      updates          476 k
 systemd-pam                                   x86_64          248.6-1.fc34                      updates          320 k
 systemd-rpm-macros                            noarch          248.6-1.fc34                      updates           28 k
 systemd-udev                                  x86_64          248.6-1.fc34                      updates          1.5 M
 urw-base35-bookman-fonts                      noarch          20200910-5.fc34                   updates          846 k
 urw-base35-c059-fonts                         noarch          20200910-5.fc34                   updates          874 k
 urw-base35-d050000l-fonts                     noarch          20200910-5.fc34                   updates           76 k
 urw-base35-fonts                              noarch          20200910-5.fc34                   updates          9.9 k
 urw-base35-fonts-common                       noarch          20200910-5.fc34                   updates           21 k
 urw-base35-gothic-fonts                       noarch          20200910-5.fc34                   updates          642 k
 urw-base35-nimbus-mono-ps-fonts               noarch          20200910-5.fc34                   updates          795 k
 urw-base35-nimbus-roman-fonts                 noarch          20200910-5.fc34                   updates          855 k
 urw-base35-nimbus-sans-fonts                  noarch          20200910-5.fc34                   updates          1.3 M
 urw-base35-p052-fonts                         noarch          20200910-5.fc34                   updates          973 k
 urw-base35-standard-symbols-ps-fonts          noarch          20200910-5.fc34                   updates           41 k
 urw-base35-z003-fonts                         noarch          20200910-5.fc34                   updates          275 k
 vim-common                                    x86_64          2:8.2.3223-1.fc34                 updates          6.7 M
 vim-enhanced                                  x86_64          2:8.2.3223-1.fc34                 updates          1.8 M
 vim-filesystem                                noarch          2:8.2.3223-1.fc34                 updates           22 k
 vim-minimal                                   x86_64          2:8.2.3223-1.fc34                 updates          698 k
 whois-nls                                     noarch          5.5.10-1.fc34                     updates           34 k
 xkeyboard-config                              noarch          2.33-1.fc34                       updates          783 k
 xrefresh                                      x86_64          1.0.6-3.fc34                      updates           23 k
 xstdcmap                                      x86_64          1.0.4-4.fc34                      updates           24 k
 xxhash-libs                                   x86_64          0.8.0-3.fc34                      updates           40 k
 yum                                           noarch          4.8.0-1.fc34                      updates           45 k
 zchunk-libs                                   x86_64          1.1.15-1.fc34                     updates           46 k
Installing dependencies:
 gperftools-libs                               x86_64          2.9.1-1.fc34                      fedora           318 k
 grub2-tools-efi                               x86_64          1:2.06-2.fc34                     updates          541 k
 grub2-tools-extra                             x86_64          1:2.06-2.fc34                     updates          840 k
 jpegxl-libs                                   x86_64          0.3.7-3.fc34                      updates          932 k
 libsodium                                     x86_64          1.0.18-7.fc34                     fedora           165 k
 rpmautospec-rpm-macros                        noarch          0.2.3-1.fc34                      updates          9.8 k
Installing weak dependencies:
 jxl-pixbuf-loader                             x86_64          0.3.7-3.fc34                      updates          414 k

Transaction Summary
========================================================================================================================Install    7 Packages
Upgrade  139 Packages

Total size: 106 M
Downloading Packages:
[SKIPPED] gperftools-libs-2.9.1-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] libsodium-1.0.18-7.fc34.x86_64.rpm: Already downloaded
[SKIPPED] grub2-tools-efi-2.06-2.fc34.x86_64.rpm: Already downloaded
[SKIPPED] grub2-tools-extra-2.06-2.fc34.x86_64.rpm: Already downloaded
[SKIPPED] jpegxl-libs-0.3.7-3.fc34.x86_64.rpm: Already downloaded
[SKIPPED] jxl-pixbuf-loader-0.3.7-3.fc34.x86_64.rpm: Already downloaded
[SKIPPED] rpmautospec-rpm-macros-0.2.3-1.fc34.noarch.rpm: Already downloaded
[SKIPPED] NetworkManager-1.30.6-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] NetworkManager-libnm-1.30.6-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] alsa-lib-1.2.5.1-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] audit-3.0.3-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] audit-libs-3.0.3-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] ca-certificates-2021.2.50-1.0.fc34.noarch.rpm: Already downloaded
[SKIPPED] coreutils-8.32-30.fc34.x86_64.rpm: Already downloaded
[SKIPPED] coreutils-common-8.32-30.fc34.x86_64.rpm: Already downloaded
[SKIPPED] cpp-11.2.1-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] cryptsetup-libs-2.3.6-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] curl-7.76.1-7.fc34.x86_64.rpm: Already downloaded
[SKIPPED] dbus-broker-29-2.fc34.x86_64.rpm: Already downloaded
[SKIPPED] dhcp-client-4.4.2-11.b1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] dhcp-common-4.4.2-11.b1.fc34.noarch.rpm: Already downloaded
[SKIPPED] distribution-gpg-keys-1.55-1.fc34.noarch.rpm: Already downloaded
[SKIPPED] dnf-4.8.0-1.fc34.noarch.rpm: Already downloaded
[SKIPPED] dnf-data-4.8.0-1.fc34.noarch.rpm: Already downloaded
[SKIPPED] dnf-plugins-core-4.0.22-1.fc34.noarch.rpm: Already downloaded
[SKIPPED] dracut-055-3.fc34.x86_64.rpm: Already downloaded
[SKIPPED] elfutils-0.185-2.fc34.x86_64.rpm: Already downloaded
[SKIPPED] elfutils-debuginfod-client-0.185-2.fc34.x86_64.rpm: Already downloaded
[SKIPPED] elfutils-default-yama-scope-0.185-2.fc34.noarch.rpm: Already downloaded
[SKIPPED] elfutils-libelf-0.185-2.fc34.x86_64.rpm: Already downloaded
[SKIPPED] elfutils-libs-0.185-2.fc34.x86_64.rpm: Already downloaded
[SKIPPED] emacs-filesystem-27.2-4.fc34.noarch.rpm: Already downloaded
[SKIPPED] expat-2.4.1-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] file-5.39-6.fc34.x86_64.rpm: Already downloaded
[SKIPPED] file-libs-5.39-6.fc34.x86_64.rpm: Already downloaded
[SKIPPED] fontconfig-2.13.94-2.fc34.x86_64.rpm: Already downloaded
[SKIPPED] gdb-minimal-10.2-3.fc34.x86_64.rpm: Already downloaded
[SKIPPED] generic-release-34-0.3.noarch.rpm: Already downloaded
[SKIPPED] generic-release-common-34-0.3.noarch.rpm: Already downloaded
[SKIPPED] glibc-2.33-20.fc34.x86_64.rpm: Already downloaded
[SKIPPED] glibc-common-2.33-20.fc34.x86_64.rpm: Already downloaded
[SKIPPED] glibc-doc-2.33-20.fc34.noarch.rpm: Already downloaded
[SKIPPED] glibc-langpack-en-2.33-20.fc34.x86_64.rpm: Already downloaded
[SKIPPED] glibc-minimal-langpack-2.33-20.fc34.x86_64.rpm: Already downloaded
[SKIPPED] gnutls-3.7.2-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] grub2-common-2.06-2.fc34.noarch.rpm: Already downloaded
[SKIPPED] grub2-tools-2.06-2.fc34.x86_64.rpm: Already downloaded
[SKIPPED] grub2-tools-minimal-2.06-2.fc34.x86_64.rpm: Already downloaded
[SKIPPED] gstreamer1-1.19.1-2.1.18.4.fc34.x86_64.rpm: Already downloaded
[SKIPPED] gtk-update-icon-cache-3.24.30-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] gtk3-3.24.30-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] ipcalc-1.0.1-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] jasper-libs-2.0.32-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] kmod-29-2.fc34.x86_64.rpm: Already downloaded
[SKIPPED] kmod-libs-29-2.fc34.x86_64.rpm: Already downloaded
[SKIPPED] krb5-libs-1.19.1-14.fc34.x86_64.rpm: Already downloaded
[SKIPPED] libX11-1.7.2-3.fc34.x86_64.rpm: Already downloaded
[SKIPPED] libX11-common-1.7.2-3.fc34.noarch.rpm: Already downloaded
[SKIPPED] libX11-xcb-1.7.2-3.fc34.x86_64.rpm: Already downloaded
[SKIPPED] libXfixes-6.0.0-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] libaom-3.1.1-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] libavif-0.9.0-2.fc34.x86_64.rpm: Already downloaded
[SKIPPED] libcomps-0.1.17-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] libcurl-7.76.1-7.fc34.x86_64.rpm: Already downloaded
[SKIPPED] libdav1d-0.9.0-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] libdnf-0.63.1-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] libeconf-0.4.0-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] libedit-3.1-38.20210714cvs.fc34.x86_64.rpm: Already downloaded
[SKIPPED] libepoxy-1.5.8-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] libgcc-11.2.1-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] libgcrypt-1.9.3-3.fc34.x86_64.rpm: Already downloaded
[SKIPPED] libgomp-11.2.1-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] libgs-9.53.3-6.fc34.x86_64.rpm: Already downloaded
[SKIPPED] libgusb-0.3.7-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] libibverbs-36.0-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] libidn2-2.3.2-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] libmodulemd-2.13.0-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] libpcap-1.10.1-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] librepo-1.14.1-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] libreport-filesystem-2.15.2-2.fc34.noarch.rpm: Already downloaded
[SKIPPED] librsvg2-2.50.6-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] libstdc++-11.2.1-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] libuser-0.63-4.fc34.x86_64.rpm: Already downloaded
[SKIPPED] libvmaf-2.1.1-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] libxcrypt-4.4.23-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] libxcrypt-compat-4.4.23-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] libxml2-2.9.12-4.fc34.x86_64.rpm: Already downloaded
[SKIPPED] mkpasswd-5.5.10-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] mpfr-4.1.0-7.fc34.x86_64.rpm: Already downloaded
[SKIPPED] netpbm-10.95.00-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] nettle-3.7.3-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] openjpeg2-2.4.0-3.fc34.x86_64.rpm: Already downloaded
[SKIPPED] openldap-2.4.57-5.fc34.x86_64.rpm: Already downloaded
[SKIPPED] openssh-8.6p1-3.fc34.x86_64.rpm: Already downloaded
[SKIPPED] openssh-clients-8.6p1-3.fc34.x86_64.rpm: Already downloaded
[SKIPPED] openssh-server-8.6p1-3.fc34.x86_64.rpm: Already downloaded
[SKIPPED] pam-1.5.1-6.fc34.x86_64.rpm: Already downloaded
[SKIPPED] pango-1.48.7-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] polkit-libs-0.117-3.fc34.1.x86_64.rpm: Already downloaded
[SKIPPED] python-setuptools-wheel-53.0.0-2.fc34.noarch.rpm: Already downloaded
[SKIPPED] python-srpm-macros-3.9-38.fc34.noarch.rpm: Already downloaded
[SKIPPED] python-unversioned-command-3.9.6-2.fc34.noarch.rpm: Already downloaded
[SKIPPED] python3-3.9.6-2.fc34.x86_64.rpm: Already downloaded
[SKIPPED] python3-dbus-1.2.18-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] python3-dnf-4.8.0-1.fc34.noarch.rpm: Already downloaded
[SKIPPED] python3-dnf-plugin-system-upgrade-4.0.15-1.fc34.noarch.rpm: Already downloaded
[SKIPPED] python3-dnf-plugins-core-4.0.22-1.fc34.noarch.rpm: Already downloaded
[SKIPPED] python3-dnf-plugins-extras-common-4.0.15-1.fc34.noarch.rpm: Already downloaded
[SKIPPED] python3-hawkey-0.63.1-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] python3-libcomps-0.1.17-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] python3-libdnf-0.63.1-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] python3-libs-3.9.6-2.fc34.x86_64.rpm: Already downloaded
[SKIPPED] python3-setuptools-53.0.0-2.fc34.noarch.rpm: Already downloaded
[SKIPPED] rav1e-libs-0.4.1-2.fc34.x86_64.rpm: Already downloaded
[SKIPPED] redhat-rpm-config-183-1.fc34.noarch.rpm: Already downloaded
[SKIPPED] rust-srpm-macros-18-1.fc34.noarch.rpm: Already downloaded
[SKIPPED] svt-av1-libs-0.8.7-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] systemd-248.6-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] systemd-libs-248.6-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] systemd-networkd-248.6-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] systemd-pam-248.6-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] systemd-rpm-macros-248.6-1.fc34.noarch.rpm: Already downloaded
[SKIPPED] systemd-udev-248.6-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] urw-base35-bookman-fonts-20200910-5.fc34.noarch.rpm: Already downloaded
[SKIPPED] urw-base35-c059-fonts-20200910-5.fc34.noarch.rpm: Already downloaded
[SKIPPED] urw-base35-d050000l-fonts-20200910-5.fc34.noarch.rpm: Already downloaded
[SKIPPED] urw-base35-fonts-20200910-5.fc34.noarch.rpm: Already downloaded
[SKIPPED] urw-base35-fonts-common-20200910-5.fc34.noarch.rpm: Already downloaded
[SKIPPED] urw-base35-gothic-fonts-20200910-5.fc34.noarch.rpm: Already downloaded
[SKIPPED] urw-base35-nimbus-mono-ps-fonts-20200910-5.fc34.noarch.rpm: Already downloaded
[SKIPPED] urw-base35-nimbus-roman-fonts-20200910-5.fc34.noarch.rpm: Already downloaded
[SKIPPED] urw-base35-nimbus-sans-fonts-20200910-5.fc34.noarch.rpm: Already downloaded
[SKIPPED] urw-base35-p052-fonts-20200910-5.fc34.noarch.rpm: Already downloaded
[SKIPPED] urw-base35-standard-symbols-ps-fonts-20200910-5.fc34.noarch.rpm: Already downloaded
[SKIPPED] urw-base35-z003-fonts-20200910-5.fc34.noarch.rpm: Already downloaded
[SKIPPED] vim-common-8.2.3223-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] vim-enhanced-8.2.3223-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] vim-filesystem-8.2.3223-1.fc34.noarch.rpm: Already downloaded
[SKIPPED] vim-minimal-8.2.3223-1.fc34.x86_64.rpm: Already downloaded
[SKIPPED] whois-nls-5.5.10-1.fc34.noarch.rpm: Already downloaded
[SKIPPED] xkeyboard-config-2.33-1.fc34.noarch.rpm: Already downloaded
[SKIPPED] xrefresh-1.0.6-3.fc34.x86_64.rpm: Already downloaded
[SKIPPED] xstdcmap-1.0.4-4.fc34.x86_64.rpm: Already downloaded
[SKIPPED] xxhash-libs-0.8.0-3.fc34.x86_64.rpm: Already downloaded
[SKIPPED] yum-4.8.0-1.fc34.noarch.rpm: Already downloaded
[SKIPPED] zchunk-libs-1.1.15-1.fc34.x86_64.rpm: Already downloaded
Running transaction check
warning: Found bdb_ro Packages database while attempting sqlite backend: using bdb_ro backend.
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
RPM: warning: Found bdb_ro Packages database while attempting sqlite backend: using bdb_ro backend.
RPM: error: cannot open Packages index using bdb_ro - Operation not permitted (1)
RPM: error: cannot open Packages database in /var/lib/rpm
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Could not run transaction.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2474  100  2474    0     0  10438      0 --:--:-- --:--:-- --:--:-- 10438
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   566  100   566    0     0   1938      0 --:--:-- --:--:-- --:--:--  1945
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   189  100   189    0     0    627      0 --:--:-- --:--:-- --:--:--   627
warning: Found bdb_ro Packages database while attempting sqlite backend: using bdb_ro backend.
warning: Found bdb_ro Packages database while attempting sqlite backend: using bdb_ro backend.
[root@NVIGBHNMJR2 maciek]#`

**Comment by crramirez** [comment]
OK there must be another thing. We will try to reproduce the error and come with a solution.

Thanks for reporting

**Comment by vobo70** [comment]
tried:
`[maciek@NVIGBHNMJR2 ~]$ sudo rpmdb --rebuilddb
warning: Converting database from bdb_ro to sqlite backend
error: failed to replace old database with new database!
error: replace files in /var/lib/rpm with files from /var/lib/rpmrebuilddb.43 to recover`
maybe I will try to delete fedora and install once again?

**Comment by crramirez** [comment]
I had this error the first time that I upgraded from 32 to 33. Do the following:

sudo cp -r /var/lib/rpmrebuilddb.43/*  /var/lib/rpm/

then go to /var/lib/rpm and delete all files that are NOT: rpmdb.sqlite*

then wsl.exe --terminate fedoraremix

and try again.

If you delete and install fedoraremix you can install directly the version 34

Regards,
Carlos

**Comment by vobo70** [comment]
thank you very much - that worked for me

**Comment by crramirez** [comment]
No worries I'll update the blog post. Also, I realized that someone made a comment there about the same situation

**Comment by vobo70** [comment]
It was me :-)

pt., 6 sie 2021 o 10:09 Carlos Rafael Ramirez ***@***.***>
napisał(a):

**Comment by crramirez** [comment]
I need to setup the comments notifications there

**Comment by liudonghua123** [comment]
> Could you try this?
> 
> `sudo rpmdb --rebuilddb`

`rpmdb --rebuilddb` works for me though some warnings.
