### ISSUE TITLE
Upgrade to F35 fails on upgrade.sh

### ISSUE THREAD

**Issue by ukulanne** [WhitewaterFoundry/Fedora-Remix-for-WSL#138]
$ upgrade.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3383  100  3383    0     0  11429      0 --:--:-- --:--:-- --:--:-- 11429
/usr/local/bin/upgrade.sh: line 79: unexpected EOF while looking for matching `"'
/usr/local/bin/upgrade.sh: line 89: syntax error: unexpected end of file
[panda@pandatlan ~]$

**Comment by crramirez** [comment]
Hello,

Thanks for reporting. Just run it again. This is because it updates itself while is running. 

We made a change to minimize that, and the new F35 image will include it.

Regards,
Carlos
