### ISSUE TITLE
Is it safe to use `dnf system-upgrade` to upgrade from store-purchased F35 app to F36/Rawhide?

### ISSUE THREAD

**Issue by GavinRay97** [WhitewaterFoundry/Fedora-Remix-for-WSL#140]
I am just curious whether this would break anything.

Below is what it wants to do when I run `sudo dnf system-upgrade download --releasever=rawhide`

<details>
<summary>CLICK TO SHOW</summary>

        [user@MSI ~]$ sudo dnf system-upgrade download --releasever=rawhide
        Before you continue ensure that your system is fully upgraded by running "dnf --refresh upgrade". Do you want to continue [y/N]: y
        Copr repo for wslu owned by wslutilities                                                609  B/s | 341  B     00:00
        Errors during downloading metadata for repository 'copr:copr.fedorainfracloud.org:wslutilities:wslu':
        - Status code: 404 for https://download.copr.fedorainfracloud.org/results/wslutilities/wslu/fedora-rawhide-x86_64/repodata/repomd.xml (IP: 13.35.118.66)
        Error: Failed to download metadata for repo 'copr:copr.fedorainfracloud.org:wslutilities:wslu': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
        determining the fastest mirror (27 hosts).. done.===                                  ] ---  B/s |   0  B     --:-- ETA
        Fedora rawhide - x86_64                                                                 4.4 MB/s |  62 MB     00:14
        Fedora rawhide openh264 (From Cisco) - x86_64                                           3.2 kB/s | 2.5 kB     00:00
        determining the fastest mirror (25 hosts).. done.               ===                   ] ---  B/s |   0  B     --:-- ETA
        Fedora Modular rawhide - x86_64                                                         340 kB/s | 1.3 MB     00:04
        Fedora rawhide - x86_64 - Updates                                                       1.6 MB/s | 1.7 MB     00:01
        Fedora Modular rawhide - x86_64 - Updates                                               178 kB/s | 156 kB     00:00
        whitewaterfoundry_fedoraremix                                                            38 kB/s |  57 kB     00:01
        whitewaterfoundry_fedoraremix-source                                                    1.0 kB/s | 1.6 kB     00:01
        Ignoring repositories: copr:copr.fedorainfracloud.org:wslutilities:wslu
        Dependencies resolved.
        ========================================================================================================================
        Package                                     Architecture  Version                                  Repository     Size
        ========================================================================================================================
        Upgrading:
        ImageMagick                                 x86_64        1:6.9.12.32-1.fc36                       fedora        163 k
        ImageMagick-libs                            x86_64        1:6.9.12.32-1.fc36                       fedora        2.3 M
        LibRaw                                      x86_64        0.20.2-3.fc36                            fedora        376 k
        NetworkManager                              x86_64        1:1.36.0-0.2.fc36                        fedora        2.2 M
        NetworkManager-libnm                        x86_64        1:1.36.0-0.2.fc36                        fedora        1.7 M
        abattis-cantarell-fonts                     noarch        0.301-4.fc36                             fedora        364 k
        adobe-mappings-cmap                         noarch        20190730-2.fc36                          fedora        2.1 M
        adobe-mappings-cmap-deprecated              noarch        20190730-2.fc36                          fedora        115 k
        adwaita-cursor-theme                        noarch        41.0-1.fc36                              fedora        626 k
        adwaita-icon-theme                          noarch        41.0-1.fc36                              fedora         11 M
        alsa-lib                                    x86_64        1.2.6.1-2.fc36                           fedora        496 k
        at-spi2-core                                x86_64        2.42.0-1.fc36                            fedora        176 k
        audit                                       x86_64        3.0.6-1.fc36                             fedora        251 k
        audit-libs                                  x86_64        3.0.6-1.fc36                             fedora        116 k
        bash                                        x86_64        5.1.8-3.fc36                             fedora        1.7 M
        bash-completion                             noarch        1:2.11-4.fc36                            fedora        291 k
        bc                                          x86_64        1.07.1-14.fc36                           fedora        118 k
        binutils                                    x86_64        2.37-22.fc36                             fedora        6.0 M
        binutils-gold                               x86_64        2.37-22.fc36                             fedora        727 k
        bzip2                                       x86_64        1.0.8-10.fc36                            fedora         52 k
        bzip2-libs                                  x86_64        1.0.8-10.fc36                            fedora         40 k
        ca-certificates                             noarch        2021.2.50-5.fc36                         fedora        353 k
        cdparanoia-libs                             x86_64        10.2-38.fc36                             fedora         54 k
        coreutils                                   x86_64        9.0-2.fc36                               fedora        1.0 M
        coreutils-common                            x86_64        9.0-2.fc36                               fedora        2.0 M
        cpio                                        x86_64        2.13-11.fc36                             fedora        270 k
        cracklib                                    x86_64        2.9.6-27.fc36                            fedora         81 k
        cracklib-dicts                              x86_64        2.9.6-27.fc36                            fedora        3.6 M
        crypto-policies                             noarch        20211115-1.git1b1c04c.fc36               fedora         58 k
        crypto-policies-scripts                     noarch        20211115-1.git1b1c04c.fc36               fedora         81 k
        cryptsetup-libs                             x86_64        2.4.2-1.fc36                             fedora        438 k
        cups-libs                                   x86_64        1:2.3.3op2-11.fc36                       fedora        266 k
        curl                                        x86_64        7.80.0-2.fc36                            fedora        309 k
        cyrus-sasl-lib                              x86_64        2.1.27-16.fc36                           fedora        774 k
        dbus                                        x86_64        1:1.12.20-5.fc36                         fedora        7.4 k
        dbus-broker                                 x86_64        29-4.fc36                                fedora        171 k
        dbus-common                                 noarch        1:1.12.20-5.fc36                         fedora         14 k
        dbus-libs                                   x86_64        1:1.12.20-5.fc36                         fedora        152 k
        dhcp-client                                 x86_64        12:4.4.2-17.P1.fc36                      fedora        788 k
        dhcp-common                                 noarch        12:4.4.2-17.P1.fc36                      fedora        126 k
        distribution-gpg-keys                       noarch        1.60-1.fc36                              fedora        340 k
        dnf                                         noarch        4.10.0-1.fc36                            fedora        448 k
        dnf-data                                    noarch        4.10.0-1.fc36                            fedora         45 k
        dnf-plugins-core                            noarch        4.0.24-1.fc36                            fedora         35 k
        dnf-utils                                   noarch        4.0.24-1.fc36                            fedora         37 k
        efi-srpm-macros                             noarch        5-4.fc36                                 fedora         22 k
        elfutils                                    x86_64        0.186-1.fc36                             fedora        521 k
        elfutils-debuginfod-client                  x86_64        0.186-1.fc36                             fedora         40 k
        elfutils-default-yama-scope                 noarch        0.186-1.fc36                             fedora         19 k
        elfutils-libelf                             x86_64        0.186-1.fc36                             fedora        200 k
        elfutils-libs                               x86_64        0.186-1.fc36                             fedora        256 k
        exempi                                      x86_64        2.6.0-0.1.20211007gite23c213.fc36        fedora        523 k
        exiv2                                       x86_64        0.27.5-1.fc36                            fedora        976 k
        exiv2-libs                                  x86_64        0.27.5-1.fc36                            fedora        777 k
        fedora-gpg-keys                             noarch        36-0.3                                   fedora        113 k
        fedora-repos                                noarch        36-0.3                                   fedora         11 k
        fedora-repos-modular                        noarch        36-0.3                                   fedora         11 k
        file                                        x86_64        5.41-2.fc36                              fedora         48 k
        file-libs                                   x86_64        5.41-2.fc36                              fedora        635 k
        filesystem                                  x86_64        3.16-1.fc36                              fedora        1.1 M
        freetype                                    x86_64        2.11.1-1.fc36                            fedora        399 k
        fribidi                                     x86_64        1.0.11-1.fc36                            fedora         52 k
        gawk                                        x86_64        5.1.1-1.fc36                             fedora        1.0 M
        gd                                          x86_64        2.3.3-4.fc36                             fedora        137 k
        gdb-minimal                                 x86_64        11.1-6.fc36                              fedora        3.8 M
        gdbm-libs                                   x86_64        1:1.22-1.fc36                            fedora         57 k
        generic-release                             noarch        36-0.1                                   fedora        7.9 k
        generic-release-common                      noarch        36-0.1                                   fedora         14 k
        glib-networking                             x86_64        2.70.1-1.fc36                            fedora        176 k
        glib2                                       x86_64        2.70.2-2.fc36                            fedora        2.6 M
        glibc                                       x86_64        2.34.9000-27.fc36                        fedora        2.0 M
        glibc-common                                x86_64        2.34.9000-27.fc36                        fedora        415 k
        glibc-gconv-extra                           x86_64        2.34.9000-27.fc36                        fedora        1.6 M
        glibc-langpack-en                           x86_64        2.34.9000-27.fc36                        fedora        695 k
        glibc-minimal-langpack                      x86_64        2.34.9000-27.fc36                        fedora        142 k
        gmp                                         x86_64        1:6.2.1-1.fc36                           fedora        314 k
        gnupg2                                      x86_64        2.3.3-2.fc36                             fedora        2.5 M
        gobject-introspection                       x86_64        1.70.0-1.fc36                            fedora        253 k
        gpgme                                       x86_64        1.15.1-6.fc36                            fedora        206 k
        gpm-libs                                    x86_64        1.20.7-39.fc36                           fedora         20 k
        graphviz                                    x86_64        2.50.0-1.fc36                            fedora        1.6 M
        grep                                        x86_64        3.7-1.fc36                               fedora        294 k
        gsettings-desktop-schemas                   x86_64        41.0-1.fc36                              fedora        688 k
        gstreamer1                                  x86_64        1.19.3-1.fc36                            fedora        1.4 M
        gstreamer1-plugins-base                     x86_64        1.19.3-1.fc36                            fedora        2.1 M
        gtk-update-icon-cache                       x86_64        3.24.30-4.fc36                           fedora         35 k
        gtk3                                        x86_64        3.24.30-4.fc36                           fedora        4.8 M
        gzip                                        x86_64        1.11-1.fc36                              fedora        154 k
        harfbuzz                                    x86_64        3.1.2-1.fc36                             fedora        706 k
        hwdata                                      noarch        0.354-1.fc36                             fedora        1.5 M
        ima-evm-utils                               x86_64        1.3.2-4.fc36                             fedora         60 k
        imath                                       x86_64        3.1.3-1.fc36                             fedora         94 k
        initscripts                                 x86_64        10.12-1.fc36                             fedora        215 k
        iproute                                     x86_64        5.15.0-1.fc36                            fedora        734 k
        iptables-legacy-libs                        x86_64        1.8.7-14.fc36                            fedora         39 k
        iso-codes                                   noarch        4.8.0-1.fc36                             fedora        3.2 M
        jasper-libs                                 x86_64        2.0.33-1.fc36                            fedora        151 k
        json-glib                                   x86_64        1.6.6-1.fc36                             fedora        151 k
        jxl-pixbuf-loader                           x86_64        0.6.1-6.fc36                             fedora         54 k
        kbd                                         x86_64        2.4.0-8.fc36                             fedora        381 k
        kbd-misc                                    noarch        2.4.0-8.fc36                             fedora        1.5 M
        kernel-srpm-macros                          noarch        1.0-13.fc36                              fedora        9.0 k
        kmod                                        x86_64        29-6.fc36                                fedora        117 k
        kmod-libs                                   x86_64        29-6.fc36                                fedora         67 k
        krb5-libs                                   x86_64        1.19.2-4.fc36                            fedora        722 k
        langpacks-core-font-en                      noarch        3.0-16.fc36                              fedora        9.2 k
        less                                        x86_64        590-2.fc36                               fedora        160 k
        libX11                                      x86_64        1.7.3.1-1.fc36                           fedora        645 k
        libX11-common                               noarch        1.7.3.1-1.fc36                           fedora        152 k
        libX11-xcb                                  x86_64        1.7.3.1-1.fc36                           fedora         11 k
        libXaw                                      x86_64        1.0.14-1.fc36                            fedora        202 k
        libXft                                      x86_64        2.3.4-1.fc36                             fedora         61 k
        libXi                                       x86_64        1.8-1.fc36                               fedora         39 k
        libXt                                       x86_64        1.2.1-1.fc36                             fedora        179 k
        libaom                                      x86_64        3.2.0-2.fc36                             fedora        1.6 M
        libarchive                                  x86_64        3.5.2-2.fc36                             fedora        387 k
        libavif                                     x86_64        0.9.3-1.fc36                             fedora         75 k
        libblkid                                    x86_64        2.37.2-1.fc36                            fedora        107 k
        libcanberra                                 x86_64        0.30-26.fc36                             fedora         85 k
        libcanberra-gtk2                            x86_64        0.30-26.fc36                             fedora         25 k
        libcanberra-gtk3                            x86_64        0.30-26.fc36                             fedora         31 k
        libcap-ng                                   x86_64        0.8.2-7.fc36                             fedora         32 k
        libcom_err                                  x86_64        1.46.4-1.fc36                            fedora         26 k
        libcomps                                    x86_64        0.1.18-1.fc36                            fedora         77 k
        libcurl                                     x86_64        7.80.0-2.fc36                            fedora        293 k
        libdav1d                                    x86_64        0.9.2-1.fc36                             fedora        472 k
        libdb                                       x86_64        5.3.28-50.fc36                           fedora        748 k
        libdnf                                      x86_64        0.65.0-1.fc36                            fedora        646 k
        libdrm                                      x86_64        2.4.109-1.fc36                           fedora        161 k
        libedit                                     x86_64        3.1-40.20210910cvs.fc36                  fedora        105 k
        libepoxy                                    x86_64        1.5.9-1.fc36                             fedora        243 k
        libevent                                    x86_64        2.1.12-5.fc36                            fedora        260 k
        libexif                                     x86_64        0.6.24-1.fc36                            fedora        460 k
        libfdisk                                    x86_64        2.37.2-1.fc36                            fedora        155 k
        libfido2                                    x86_64        1.9.0-1.fc36                             fedora         94 k
        libfontenc                                  x86_64        1.1.4-2.fc36                             fedora         31 k
        libfsverity                                 x86_64        1.4-6.fc36                               fedora         19 k
        libgcc                                      x86_64        11.2.1-7.fc36                            fedora        112 k
        libgcrypt                                   x86_64        1.9.4-1.fc36                             fedora        507 k
        libgexiv2                                   x86_64        0.14.0-1.fc36                            fedora         95 k
        libglvnd                                    x86_64        1:1.3.4-2.fc36                           fedora        135 k
        libglvnd-egl                                x86_64        1:1.3.4-2.fc36                           fedora         36 k
        libglvnd-glx                                x86_64        1:1.3.4-2.fc36                           fedora        142 k
        libgomp                                     x86_64        11.2.1-7.fc36                            fedora        285 k
        libgpg-error                                x86_64        1.43-1.fc36                              fedora        216 k
        libgs                                       x86_64        9.55.0-1.fc36                            fedora        3.5 M
        libgudev                                    x86_64        237-1.fc36                               fedora         35 k
        libgusb                                     x86_64        0.3.9-1.fc36                             fedora         51 k
        libibverbs                                  x86_64        38.0-1.fc36                              fedora        391 k
        libidn2                                     x86_64        2.3.2-3.fc36                             fedora        103 k
        libimagequant                               x86_64        2.17.0-1.fc36                            fedora         62 k
        libimobiledevice                            x86_64        1.3.0-5.fc36                             fedora         75 k
        libjpeg-turbo                               x86_64        2.1.2-1.fc36                             fedora        176 k
        libjxl                                      x86_64        0.6.1-6.fc36                             fedora        971 k
        libmodulemd                                 x86_64        2.13.0-3.fc36                            fedora        231 k
        libmount                                    x86_64        2.37.2-1.fc36                            fedora        135 k
        libnghttp2                                  x86_64        1.46.0-1.fc36                            fedora         70 k
        libnsl2                                     x86_64        2.0.0-2.fc36                             fedora         30 k
        libpipeline                                 x86_64        1.5.4-1.fc36                             fedora         51 k
        libpwquality                                x86_64        1.4.4-6.fc36                             fedora        104 k
        libraqm                                     x86_64        0.7.2-1.fc36                             fedora         19 k
        librepo                                     x86_64        1.14.2-1.fc36                            fedora         95 k
        librsvg2                                    x86_64        2.52.4-1.fc36                            fedora        3.6 M
        libseccomp                                  x86_64        2.5.3-1.fc36                             fedora         71 k
        libselinux                                  x86_64        3.3-2.fc36                               fedora         84 k
        libsemanage                                 x86_64        3.3-1.fc36                               fedora        116 k
        libsepol                                    x86_64        3.3-2.fc36                               fedora        301 k
        libsmartcols                                x86_64        2.37.2-1.fc36                            fedora         64 k
        libsndfile                                  x86_64        1.0.31-6.fc36                            fedora        206 k
        libsolv                                     x86_64        0.7.20-1.fc36                            fedora        399 k
        libsoup                                     x86_64        2.74.2-1.fc36                            fedora        390 k
        libssh                                      x86_64        0.9.6-1.fc36                             fedora        203 k
        libssh-config                               noarch        0.9.6-1.fc36                             fedora        7.3 k
        libstdc++                                   x86_64        11.2.1-7.fc36                            fedora        747 k
        libtasn1                                    x86_64        4.18.0-1.fc36                            fedora         74 k
        libtirpc                                    x86_64        1.3.2-1.rc1.fc36                         fedora         93 k
        libtool-ltdl                                x86_64        2.4.6-45.fc36                            fedora         36 k
        libtracker-sparql                           x86_64        3.2.1-1.fc36                             fedora        350 k
        libuuid                                     x86_64        2.37.2-1.fc36                            fedora         28 k
        libvmaf                                     x86_64        2.3.0-1.fc36                             fedora        177 k
        libwebp                                     x86_64        1.2.1-1.fc36                             fedora        278 k
        libxcrypt                                   x86_64        4.4.26-4.fc36                            fedora        117 k
        libxkbcommon                                x86_64        1.3.1-1.fc36                             fedora        140 k
        libxslt                                     x86_64        1.1.34-6.fc36                            fedora        241 k
        llvm-libs                                   x86_64        13.0.0-6.fc36                            fedora         23 M
        mesa-libEGL                                 x86_64        21.3.1-2.fc36                            fedora        121 k
        mesa-libgbm                                 x86_64        21.3.1-2.fc36                            fedora         44 k
        mesa-vulkan-drivers                         x86_64        21.3.1-2.fc36                            fedora        5.6 M
        netpbm                                      x86_64        10.96.00-1.fc36                          fedora        185 k
        nspr                                        x86_64        4.32.0-4.fc36                            fedora        138 k
        nss                                         x86_64        3.73.0-1.fc36                            fedora        689 k
        nss-softokn                                 x86_64        3.73.0-1.fc36                            fedora        378 k
        nss-softokn-freebl                          x86_64        3.73.0-1.fc36                            fedora        324 k
        nss-sysinit                                 x86_64        3.73.0-1.fc36                            fedora         21 k
        nss-util                                    x86_64        3.73.0-1.fc36                            fedora         89 k
        openexr-libs                                x86_64        3.1.3-1.fc36                             fedora        1.1 M
        openldap                                    x86_64        2.4.59-4.fc36                            fedora        257 k
        openssh                                     x86_64        8.8p1-1.fc36                             fedora        450 k
        openssh-clients                             x86_64        8.8p1-1.fc36                             fedora        697 k
        openssh-server                              x86_64        8.8p1-1.fc36                             fedora        452 k
        openssl-libs                                x86_64        1:3.0.0-1.fc36                           fedora        2.1 M
        orc                                         x86_64        0.4.31-6.fc36                            fedora        182 k
        osinfo-db                                   noarch        20211013-1.fc36                          fedora        247 k
        pam                                         x86_64        1.5.2-7.fc36                             fedora        547 k
        pango                                       x86_64        1.50.0-1.fc36                            fedora        333 k
        pcre                                        x86_64        8.45-1.fc36                              fedora        197 k
        pcre2                                       x86_64        10.39-1.fc36                             fedora        231 k
        pcre2-syntax                                noarch        10.39-1.fc36                             fedora        144 k
        poppler-data                                noarch        0.4.11-1.fc36                            fedora        2.0 M
        popt                                        x86_64        1.18-6.fc36                              fedora         58 k
        publicsuffix-list-dafsa                     noarch        20210518-3.fc36                          fedora         58 k
        pulseaudio-libs                             x86_64        15.0-4.fc36                              fedora        666 k
        python-pip-wheel                            noarch        21.3.1-1.fc36                            fedora        1.1 M
        python-setuptools-wheel                     noarch        58.5.3-1.fc36                            fedora        503 k
        python-srpm-macros                          noarch        3.10-14.fc36                             fedora         25 k
        python-systemd-doc                          x86_64        234-19.fc36                              fedora        157 k
        python3                                     x86_64        3.10.1-1.fc36                            fedora         26 k
        python3-dnf                                 noarch        4.10.0-1.fc36                            fedora        417 k
        python3-dnf-plugin-versionlock              noarch        4.0.24-1.fc36                            fedora         28 k
        python3-dnf-plugins-core                    noarch        4.0.24-1.fc36                            fedora        211 k
        python3-gpg                                 x86_64        1.15.1-6.fc36                            fedora        261 k
        python3-hawkey                              x86_64        0.65.0-1.fc36                            fedora        112 k
        python3-libcomps                            x86_64        0.1.18-1.fc36                            fedora         48 k
        python3-libdnf                              x86_64        0.65.0-1.fc36                            fedora        781 k
        python3-libs                                x86_64        3.10.1-1.fc36                            fedora        7.5 M
        python3-rpm                                 x86_64        4.17.0-1.fc36.1                          fedora         92 k
        python3-systemd                             x86_64        234-19.fc36                              fedora         84 k
        rav1e-libs                                  x86_64        0.5.0-1.fc36                             fedora        881 k
        redhat-rpm-config                           noarch        206-1.fc36                               fedora         67 k
        rpm                                         x86_64        4.17.0-1.fc36.1                          fedora        538 k
        rpm-build                                   x86_64        4.17.0-1.fc36.1                          fedora         61 k
        rpm-build-libs                              x86_64        4.17.0-1.fc36.1                          fedora         93 k
        rpm-libs                                    x86_64        4.17.0-1.fc36.1                          fedora        314 k
        rpm-sign-libs                               x86_64        4.17.0-1.fc36.1                          fedora         27 k
        rsync                                       x86_64        3.2.3-13.fc36                            fedora        389 k
        rust-srpm-macros                            noarch        20-1.fc36                                fedora        9.5 k
        shadow-utils                                x86_64        2:4.9-8.fc36                             fedora        1.1 M
        sqlite-libs                                 x86_64        3.36.0-4.fc36                            fedora        632 k
        sudo                                        x86_64        1.9.8-4.p2.fc36                          fedora        1.1 M
        systemd                                     x86_64        250~rc1-2.fc36                           fedora        4.2 M
        systemd-libs                                x86_64        250~rc1-2.fc36                           fedora        630 k
        systemd-oomd-defaults                       noarch        250~rc1-2.fc36                           fedora         26 k
        systemd-pam                                 x86_64        250~rc1-2.fc36                           fedora        333 k
        systemd-resolved                            x86_64        250~rc1-2.fc36                           fedora        271 k
        systemd-rpm-macros                          noarch        250~rc1-2.fc36                           fedora         28 k
        systemd-udev                                x86_64        250~rc1-2.fc36                           fedora        1.8 M
        tpm2-tss                                    x86_64        3.1.0-4.fc36                             fedora        585 k
        tracker                                     x86_64        3.2.1-1.fc36                             fedora        532 k
        tracker-miners                              x86_64        3.2.1-1.fc36                             fedora        873 k
        tzdata                                      noarch        2021e-1.fc36                             fedora        431 k
        unzip                                       x86_64        6.0-54.fc36                              fedora        179 k
        upower                                      x86_64        0.99.13-1.fc36                           fedora        167 k
        urw-base35-bookman-fonts                    noarch        20200910-9.fc36                          fedora        846 k
        urw-base35-c059-fonts                       noarch        20200910-9.fc36                          fedora        874 k
        urw-base35-d050000l-fonts                   noarch        20200910-9.fc36                          fedora         76 k
        urw-base35-fonts                            noarch        20200910-9.fc36                          fedora         10 k
        urw-base35-fonts-common                     noarch        20200910-9.fc36                          fedora         21 k
        urw-base35-gothic-fonts                     noarch        20200910-9.fc36                          fedora        643 k
        urw-base35-nimbus-mono-ps-fonts             noarch        20200910-9.fc36                          fedora        795 k
        urw-base35-nimbus-roman-fonts               noarch        20200910-9.fc36                          fedora        856 k
        urw-base35-nimbus-sans-fonts                noarch        20200910-9.fc36                          fedora        1.3 M
        urw-base35-p052-fonts                       noarch        20200910-9.fc36                          fedora        973 k
        urw-base35-standard-symbols-ps-fonts        noarch        20200910-9.fc36                          fedora         42 k
        urw-base35-z003-fonts                       noarch        20200910-9.fc36                          fedora        276 k
        util-linux                                  x86_64        2.37.2-1.fc36                            fedora        2.2 M
        util-linux-core                             x86_64        2.37.2-1.fc36                            fedora        434 k
        vim-common                                  x86_64        2:8.2.3755-1.fc36                        fedora        6.7 M
        vim-data                                    noarch        2:8.2.3755-1.fc36                        fedora         28 k
        vim-enhanced                                x86_64        2:8.2.3755-1.fc36                        fedora        1.9 M
        vim-filesystem                              noarch        2:8.2.3755-1.fc36                        fedora         22 k
        vim-minimal                                 x86_64        2:8.2.3755-1.fc36                        fedora        708 k
        vulkan-loader                               x86_64        1.2.198.0-1.fc36                         fedora        124 k
        wget                                        x86_64        1.21.2-2.fc36                            fedora        775 k
        which                                       x86_64        2.21-31.fc36                             fedora         41 k
        xkeyboard-config                            noarch        2.34-1.fc36                              fedora        782 k
        xxhash-libs                                 x86_64        0.8.1-1.fc36                             fedora         40 k
        yum                                         noarch        4.10.0-1.fc36                            fedora         43 k
        zchunk-libs                                 x86_64        1.1.15-3.fc36                            fedora         46 k
        Installing dependencies:
        dracut                                      x86_64        055-7.fc36                               fedora        347 k
        fedora-repos-rawhide                        noarch        36-0.3                                   fedora         10 k
        fedora-repos-rawhide-modular                noarch        36-0.3                                   fedora         11 k
        fuse-libs                                   x86_64        2.9.9-13.fc35                            fedora         97 k
        gettext                                     x86_64        0.21-9.fc36                              fedora        1.1 M
        gettext-libs                                x86_64        0.21-9.fc36                              fedora        303 k
        grub2-common                                noarch        1:2.06-11.fc36                           fedora        931 k
        grub2-tools                                 x86_64        1:2.06-11.fc36                           fedora        1.8 M
        grub2-tools-minimal                         x86_64        1:2.06-11.fc36                           fedora        602 k
        initscripts-service                         noarch        10.12-1.fc36                             fedora         13 k
        libbpf                                      x86_64        2:0.5.0-1.fc36                           fedora        146 k
        libkcapi                                    x86_64        1.3.1-3.fc35                             fedora         46 k
        libkcapi-hmaccalc                           x86_64        1.3.1-3.fc35                             fedora         24 k
        libsecret                                   x86_64        0.20.4-3.fc35                            fedora        157 k
        mozjs78                                     x86_64        78.15.0-1.fc36                           fedora        8.2 M
        openssl1.1                                  x86_64        1:1.1.1l-1.fc36                          fedora        1.5 M
        os-prober                                   x86_64        1.77-8.fc35                              fedora         43 k
        pcsc-lite                                   x86_64        1.9.5-1.fc36                             fedora         91 k
        pcsc-lite-libs                              x86_64        1.9.5-1.fc36                             fedora         27 k
        polkit                                      x86_64        0.120-1.fc36                             fedora        146 k
        polkit-libs                                 x86_64        0.120-1.fc36                             fedora         66 k
        polkit-pkla-compat                          x86_64        0.1-20.fc35                              fedora         44 k
        protobuf-c                                  x86_64        1.4.0-3.fc36                             fedora         35 k
        unbound-libs                                x86_64        1.13.2-4.fc36                            fedora        536 k
        whois-nls                                   noarch        5.5.10-2.fc35                            fedora         33 k
        Installing weak dependencies:
        deltarpm                                    x86_64        3.6.2-10.fc35                            fedora         88 k
        gawk-all-langpacks                          x86_64        5.1.1-1.fc36                             fedora        231 k
        gnupg2-smime                                x86_64        2.3.3-2.fc36                             fedora        243 k
        grubby                                      x86_64        8.40-55.fc35                             fedora         35 k
        kpartx                                      x86_64        0.8.7-3.fc36                             fedora         48 k
        libxcrypt-compat                            x86_64        4.4.26-4.fc36                            fedora         89 k
        memstrack                                   x86_64        0.2.4-1.fc36                             fedora         50 k
        mkpasswd                                    x86_64        5.5.10-2.fc35                            fedora         40 k
        nano                                        x86_64        5.9-1.fc36                               fedora        686 k
        openssl-pkcs11                              x86_64        0.4.11-7.fc36                            fedora         73 k
        pcsc-lite-ccid                              x86_64        1.4.36-2.fc36                            fedora        305 k
        pigz                                        x86_64        2.6-1.fc36                               fedora         81 k
        pinentry                                    x86_64        1.2.0-1.fc36                             fedora         97 k
        python-unversioned-command                  noarch        3.10.1-1.fc36                            fedora        9.5 k
        python3-unbound                             x86_64        1.13.2-4.fc36                            fedora         99 k
        qrencode-libs                               x86_64        4.0.2-8.fc35                             fedora         58 k
        rpm-plugin-systemd-inhibit                  x86_64        4.17.0-1.fc36.1                          fedora         21 k
        sqlite                                      x86_64        3.36.0-4.fc36                            fedora        764 k
        sudo-python-plugin                          x86_64        1.9.8-4.p2.fc36                          fedora         56 k
        systemd-networkd                            x86_64        250~rc1-2.fc36                           fedora        556 k
        Downgrading:
        libffi                                      x86_64        3.1-28.fc34                              fedora         33 k
        zram-generator                              x86_64        1.1.1-2.fc36                             fedora        395 k
        zram-generator-defaults                     noarch        1.1.1-2.fc36                             fedora        9.5 k
        Upgrading Groups:
        Buildsystem building group
        Core

        Transaction Summary
        ========================================================================================================================
        Install     45 Packages
        Upgrade    278 Packages
        Downgrade    3 Packages

        Total download size: 213 M
        DNF will only download packages, install gpg keys, and check the transaction.

</details>

**Comment by crramirez** [comment]
Hello @GavinRay97,

You can follow these instructions: https://www.whitewaterfoundry.com/blog/2019/11/3/upgrade-fedora-remix-for-wsl-to-35 changing 35 by rawhide.

Just make a backup first.

I upgraded to rawhide about one year ago with this method without issues.

Regards,
Carlos

**Comment by GavinRay97** [comment]
Thank you!
