### ISSUE TITLE
Getting ssl certification problem

### ISSUE THREAD

**Issue by vijayet1** [WhitewaterFoundry/Fedora-Remix-for-WSL#141]
**Describe the bug**
When updating using dnf, getting [SSL certificate problem]

**To Reproduce**
1. exceute command 'dnf upgrade -y'
Copr repo for wslu owned by wslutilities                                                0.0  B/s |   0  B     00:00
Errors during downloading metadata for repository 'copr:copr.fedorainfracloud.org:wslutilities:wslu':
  - Curl error (60): SSL peer certificate or SSH remote key was not OK for https://download.copr.fedorainfracloud.org/results/wslutilities/wslu/fedora-35-x86_64/repodata/repomd.xml [SSL certificate problem: unable to get local issuer certificate]
Error: Failed to download metadata for repo 'copr:copr.fedorainfracloud.org:wslutilities:wslu': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Fedora 35 - x86_64                                                                      0.0  B/s |   0  B     00:04
Errors during downloading metadata for repository 'fedora':
  - Curl error (60): SSL peer certificate or SSH remote key was not OK for https://mirrors.fedoraproject.org/metalink?repo=fedora-35&arch=x86_64 [SSL certificate problem: unable to get local issuer certificate]
Error: Failed to download metadata for repo 'fedora': Cannot prepare internal mirrorlist: Curl error (60): SSL peer certificate or SSH remote key was not OK for https://mirrors.fedoraproject.org/metalink?repo=fedora-35&arch=x86_64 [SSL certificate problem: unable to get local issuer certificate]
**Expected behavior**
Should download required repo files.

**WLinux Version**

Linux DESKTOP-EHBUBJK 5.10.60.1-microsoft-standard-WSL2

**Windows Build**

OS Name:                   Microsoft Windows 11 Enterprise
OS Version:                10.0.22000 N/A Build 22000
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free

**Comment by vijayet1** [comment]
Sorry, got the issue fixed

**Comment by gablinuxIT** [comment]
Which was the solution  ¿?

**Comment by crramirez** [comment]
Usually this error get solved by itself because it is a pro lem that happens when the Fedora repos are refreshing.

Another cause could be an enabled corporate vpn
