### ISSUE TITLE
403 errors when hitting the whitewaterfoundry_fedoraremix repo

### ISSUE THREAD

**Issue by jpowner** [WhitewaterFoundry/Fedora-Remix-for-WSL#161]
**Describe the bug**

It appears that I'm not able to access the whitewaterfoundry_fedoraremix repository. 
```
[powner@NBWIN0216 ~]$ sudo dnf upgrade
whitewaterfoundry_fedoraremix                                                                                                                                                                                791  B/s | 919  B     00:01
Errors during downloading metadata for repository 'whitewaterfoundry_fedoraremix':
  - Status code: 403 for https://d28dx6y1hfq314.cloudfront.net/10303/13834/fedora/35/x86_64/repodata/2a7e208152636e124877e0f74e8b10436041bf1c3fa8492e55a58e384a98d649-repomd.xml?t=1653356528_4ee3660f395bb4ca560c07f204a58f0f55652b3e (IP: 54.192.100.95)
  - Status code: 403 for https://d28dx6y1hfq314.cloudfront.net/10303/13834/fedora/35/x86_64/repodata/2a7e208152636e124877e0f74e8b10436041bf1c3fa8492e55a58e384a98d649-repomd.xml?t=1653356527_f6aba3c995303f81c1efc8370cfe8e1d0933fbf9 (IP: 54.192.100.95)
Error: Failed to download metadata for repo 'whitewaterfoundry_fedoraremix': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```
```
[powner@NBWIN0216 ~]$ curl https://d28dx6y1hfq314.cloudfront.net/10303/13834/fedora/35/x86_64/repodata/2a7e208152636e124877e0f74e8b10436041bf1c3fa8492e55a58e384a98d649-repomd.xml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: hfkNT__tQA3RVMh57MsvNKMZdMgHTunEe-VbpGCrieH_axwfCe4g-Q==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
```
```
[powner@NBWIN0216 ~]$ cat /etc/yum.repos.d/whitewaterfoundry_fedoraremix.repo
[whitewaterfoundry_fedoraremix]
name=whitewaterfoundry_fedoraremix
baseurl=https://packagecloud.io/whitewaterfoundry/fedoraremix/fedora/35/$basearch
repo_gpgcheck=0
gpgcheck=0
enabled=1
gpgkey=https://packagecloud.io/whitewaterfoundry/fedoraremix/gpgkey
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
metadata_expire=300

[whitewaterfoundry_fedoraremix-source]
name=whitewaterfoundry_fedoraremix-source
baseurl=https://packagecloud.io/whitewaterfoundry/fedoraremix/fedora/35/SRPMS
repo_gpgcheck=0
gpgcheck=0
enabled=1
gpgkey=https://packagecloud.io/whitewaterfoundry/fedoraremix/gpgkey
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
metadata_expire=300
```

**To Reproduce**
Any update command will trigger this.

**Expected behavior**
I should be able to reach the repository and update successfully.

**Screenshots**

**Additional context**
I am not using a VPN.

**Basic Troubleshooting Checklist**

[ x ] I have searched Google for the error message.
[ x ] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[ x ] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[ x ] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
[ x ] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
[ x ] I have disabled and re-enabled WSL in Windows Features.
[ x ] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here: I have reinstalled WSL 2. Also, I am able to get updates from other repositories and update by disabling whitewaterfoundry_fedoraremix and whitewaterfoundry_fedoraremix-source.

**WLinux Version**

Find: Settings->Apps->Apps & features->WLinux->Advanced Options->Version.

Insert here: 36.0.4.0

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:

```
PS C:\Windows\system32> systeminfo | findstr /C:"OS"
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19044 N/A Build 19044
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              Dell Inc. 1.7.0, 27/05/2021
```

**Comment by jpowner** [comment]
I think it could be my ISP. Every now and then I get weird 403 errors to certain sites like petfinder.

**Comment by hongyuanjia** [comment]
Same problem here. I was unable to run dnf update due to the same error, no matter under a VPN or not. I found similar related issues #127 #149. I can curl the whitewaterfoundry_fedoraremix repository but still ran `sudo dnf update` returned timeout error. Note that I have to use a VPN in order to get access to GitHub.

The workaround for me is to add the `proxy` field in the `/etc/dnf/dnf.conf`.
