### ISSUE TITLE
No audio / does not set PULSE_SERVER

### ISSUE THREAD

**Issue by monreal** [WhitewaterFoundry/Fedora-Remix-for-WSL#165]
**Describe the bug**
Out of the box, Fedora Remix does not support audio output.

**To Reproduce**
1. install audio app
2. play sound

**Expected behavior**
Should be able to hear audio.

**Additional context**
The problem is that PULSE_SERVER is not set. Other distributions like Ubuntu export PULSE_SERVER=/mnt/wslg/PulseServer which makes audio work on Fedora Remix as well.

**WLinux Version**
36.0.4.0

**Windows Build**
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22000 N/A Build 22000
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free

**Comment by crramirez** [comment]
It should. We will take a look.

Thanks for reporting.

**Comment by monreal** [comment]
> Hello @monreal ,
> 
> Are you starting Fedora Remix with SystemD?

Yes, that seems to be the problem. I tried the systemd version in order to try flatpak apps (which actually work fine with systemd)

**Comment by crramirez** [comment]
OK, good. We will add this variable to the SystemD configuration and make a test.

On the other hand, try the flatpak app without SystemD, as I understand it works.

Regards

**Comment by monreal** [comment]
> On the other hand, try the flatpak app without SystemD, as I understand it works.

At least the one I just tried does not: "Error: Could not connect: No such file or directory" while it starts just fine using the systemd version.

**Comment by crramirez** [comment]
Hello @monreal,

We fixed the issue and tested with Spotify installed as a flatpak.

Just run ´update.sh´ to update the scripts for SystemD

Regards,
Carlos

**Comment by monreal** [comment]
I can confirm the fix, thanks!
