### ISSUE TITLE
With remote session xrdp, any of the altgr character is writable

### ISSUE THREAD

**Issue by Lanyaid** [WhitewaterFoundry/Fedora-Remix-for-WSL#166]
**Describe the bug**
Into a localhost console all seems good. In a terminal in rdp session, any of the altgr characters combination does work but #.

**To Reproduce**
1. Setup a fresh install of fedoraremix.
2. Install rdp server with fedoraremix procedure (avahi+xrdp) in order to open an x session with a rdpclient in localhost, located in https://www.whitewaterfoundry.com/blog/2022/4/16/announcing-built-in-systemd-support-in-fedora-remix-for-wsl

**Expected behavior**
To be able to write | or @ characters into a terminal in a xrdp session.

**Screenshots**
1srt screen, in a local console, i have pulsed altgr+º123456 keys to write without any problem charaters : \|@#~€¬
2nd screen into remote session from localhost (same material, same keyboard etc...), same combination of keys gave: 
`<nothing><nothing><strange command result>#<strange command result><unkown carater><unkown carater>`

![image](https://user-images.githubusercontent.com/44942052/180183239-ee8da0b5-c2f0-4fb3-8641-c1efb97ca387.png)

![image](https://user-images.githubusercontent.com/44942052/180183845-d244c883-c2df-41fc-80b1-1013efc9c002.png)

**Additional context**
Windows language is french. Keyboard is spanish and configured as spanish keyboard in windows. (I'm french but working in spain for the reason why it's configured like that)
I tried a lot of things that I found in websites but nothing worked. As I don't know what is the problem, it's not easy to apply a solution.

some more things i can give:

![image](https://user-images.githubusercontent.com/44942052/180186224-ce2b6b19-55dd-4d10-9384-01a00969cf66.png)

![image](https://user-images.githubusercontent.com/44942052/180186740-f12bd989-677b-4b7f-b60c-35ae80739d99.png)

![image](https://user-images.githubusercontent.com/44942052/180187088-196ff4dd-f2f4-43c8-bae3-77bbd69c4f70.png)

![image](https://user-images.githubusercontent.com/44942052/180187638-d7395b1d-0734-495d-b387-b04dc2044501.png)

![image](https://user-images.githubusercontent.com/44942052/180194137-21cf4fae-d25e-4655-9fff-c92f1b1591cc.png)
* Key release 36 is because I validate the command pressing enter, the test starts and I release enter key, so 36 is the number for enter key.
* 108 is the number of my altgr key.
* 248 is the number of my pipe character key when I press altgr at the same time
* 10 is the number of the "1" character key, the same as pipe character key, when I don-t press nothing else that 1.
* 64 is the number of my left alt key. 
* 
![image](https://user-images.githubusercontent.com/44942052/180187917-d474937a-09d8-48d6-a3ae-d9a58eb207ae.png)

![image](https://user-images.githubusercontent.com/44942052/180188292-c2107c07-19c6-4ee6-a3cf-22d259768e8e.png)

![image](https://user-images.githubusercontent.com/44942052/180190149-7f272ac1-0a3a-4ad5-b698-687f4b15a1d8.png)

![image](https://user-images.githubusercontent.com/44942052/180191017-c2d2575a-24a5-4e0d-b26f-de7755c98394.png)

![image](https://user-images.githubusercontent.com/44942052/180192147-1ba0ab1c-6e1a-4842-9451-8e49d7e06486.png)

**Basic Troubleshooting Checklist**

As last test I did, is to change the level 3 key from right alt to right alt as a composed by key (Shift + Right Alt is the composed key) in gnome-tweaks and I am able to write some characters with alt gr pressed (I think something like English keyboard).
From left to right, all the numerics keys of the top of the keyboard
![image](https://user-images.githubusercontent.com/44942052/180197521-7c1a530a-eb88-4003-9de2-967adc4a8f1c.png)

What other troubleshooting have you attempted?
With Windows Remote Desktop, I tried to not send the special characters in the tab "local ressources" putting "only in localhost" when special combination of keys are used.
I tried to use another Remote Desktop Client (mRemoteNG)

Insert here:

**WLinux Version**

cat /etc/os-release
```
NAME="Fedora Remix for WSL"
VERSION="36"
ID=fedoraremixforwsl
ID_LIKE=fedora
VERSION_ID=36
PLATFORM_ID="platform:f36"
PRETTY_NAME="Fedora Remix for WSL"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:36"
HOME_URL="https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL"
SUPPORT_URL="https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL"
BUG_REPORT_URL="https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL/issues"
PRIVACY_POLICY_URL="https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL/blob/master/PRIVACY.md"
FEDORA_REMIX_VERSION=36.0.4
```

Find: Settings->Apps->Apps & features->WLinux->Advanced Options->Version.
Insert here:

![image](https://user-images.githubusercontent.com/44942052/180215556-eda8b546-6672-4a85-a909-47b5b7ef3f42.png)

**Windows Build**

![image](https://user-images.githubusercontent.com/44942052/180197969-d80ae47b-75da-45b2-9c93-5e7a3449f895.png)

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:
```
systeminfo | findstr /C:"OS"
Version du BIOS:                                HP Q83 Ver. 01.19.00, 13/01/2022
```

For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**Comment by crramirez** [comment]
Hello @Lanyaid,

Very good findings and excellent explanation. We will try to reproduce and find a solution.

Regards,
Carlos

**Comment by Lanyaid** [comment]
Thanks :-)
as last thing to say, they are a lot of similars things in the web, but nothing very concluant at all. Or nothing that I could understand and say "eureka!" that is that thing or that other wich is missconfigured or giving the problem.
googling something like "wsl altgr" gives some more information

**Comment by Lanyaid** [comment]
Hi there, any update with that?
someone else has a similar problem?

**Comment by crramirez** [comment]
Hello @Lanyaid,

I can reproduce the problem in Fedora Remix, but still, we couldn't find the solution. The good news is that it doesn't happen with Pengwin with XFCE. So, the task may be can be reduced to look for what are the differences.

I'll keep you posted when we find something.

Regards,
Carlos

**Comment by Lanyaid** [comment]
Great news, at least that you can reproduce it :-). 
thx a lot for the work, I'm still waiting for more good news, so :-D!!

**Comment by crramirez** [comment]
Hello @Lanyaid 

The problem is that Windows sends Ctrl+Alt+Shift through RDP when you press AltGr. I found this page that has a solution that modifies the default mappings for XRDP:

http://c-nergy.be/blog/?p=3858

So, for the Spanish keyboard, you need to replace the content of the file: **/etc/xrdp/km-0000040a.ini** 
By: [c-nergy.be/downloads/km-040a.ini](http://c-nergy.be/downloads/km-040a.ini)

Then reconnect the session.

For other languages, the page provides the mappings.

Hope it helps

**Comment by Lanyaid** [comment]
Hi Carlos,

thx for your work and your answer. 

It works like a charm!!! thank you!

I thought it was on the xrdp side that I had the problem, but I couldn’t figure out what exactly...
You put your finger exactly on the problem.

Muchas gracias y muy buen trabajo.
