### ISSUE TITLE
Fedora remix 36 for cgroups v2

### ISSUE THREAD

**Issue by jgmarce** [WhitewaterFoundry/Fedora-Remix-for-WSL#167]
It isn't clear if Fedora remix 36 is ready for cgroups v2 or the steps to assure that it is.   Documentation for Fedora suggests that /sys/fs/cgroup/cgroup.controllers should exist by default.   Where does one find steps to configure the system for cgroups v2 please?

**Comment by crramirez** [comment]
Hello @jgmarce,

Control Group v2 is not fully supported in WSL2 and needs workarounds to make it work. Please send me your Windows version 10 or 11 to paste the instructions here. In Windows 11 is failing and only partial support can be achieved.

Regards,
Carlos

**Comment by jgmarce** [comment]
Windows Pro	10.0.19043 Build 19043

Hello @crramirez    This issue has been discussed for years now.  I don't want to regurgitate outdated instructions that I've found.   I see that Fedora remix 36 and Ubuntu 22.04 are systemd ready with cgroups v1 mounts at first boot.   I'm hopeful for clear instructions for each to enable cgroups v2 that are not muddied up by the struggles of the past.   The end goal for me includes delegation, kubernetes + cilium + istio.

**Comment by jgmarce** [comment]
@crramirez Carlos, did you need me to message you directly for windows 10 instructions that should work and then I can post only what worked for Build 19043?

**Comment by crramirez** [comment]
Hello @jgmarce,

I am sorry we are in the middle of a release and I haven't had time to build and test the instructions to send them to you.

I can send them by the end of the week.

Thank you for your patience.

Regards,
Carlos

**Comment by jgmarce** [comment]
I remain hopeful... thank you

**Comment by crramirez** [comment]
Hello @jgmarce,

Here are the instructions for Fedora Remix running in Windows 10 only.

Edit .wslconfig 
```bash
vim winhome/.wslconfig
```

And add the following under the `[wsl2]` section:
```ini
kernelCommandLine = group_no_v1=all
```
The spaces surrounding the first = are mandatory.

Add the following to your `/etc/fstab`

```
cgroup2 /sys/fs/cgroup cgroup2 rw,nosuid,nodev,noexec,relatime,nsdelegate 0 0
```

Terminate wsl2:

```bash
wsl.exe --shutdown
```

Then start Fedora Remix for WSL (SystemD).

I made the test running docker inside Fedora remix with systemD:

![image](https://user-images.githubusercontent.com/8397379/184515216-08334953-a4fb-4b8b-b16f-f17a943f8181.png)

**Comment by jgmarce** [comment]
What could be more simple?    I hope we can get the word out...   Thank you.

**Comment by jgmarce** [comment]
I have been successful.   I followed this with a podman installation, which now uses "crun" and is expected to switch to cgroups v2.  A small workaround was necessary, it took some time to find so I'll say thank you and include that as we close this out...

[jad@LAPTOP-9I22SC7L ~]$ systemd-run --scope --user podman  run -it --security-opt seccomp=unconfined public.ecr.aws/ama
zonlinux/amazonlinux:2022 /bin/bash
Running scope as unit: run-r9b74e639abda458a967414f2d7e66ffa.scope
Error: OCI runtime error: crun: the requested cgroup controller `pids` is not available
[jad@LAPTOP-9I22SC7L ~]$

The fix:
configure pids_limit=0 under [containers] in /etc/containers/containers.conf (until https://bugzilla.redhat.com/show_bug.cgi?id=1897579 is fixed)


$ systemd-run --scope --user podman  run -it --security-opt seccomp=unconfined public.ecr.aws/ama
zonlinux/amazonlinux:2022 /bin/bash
Running scope as unit: run-r0e9d27f8a42d4681ab2fb008cff30f43.scope
bash-5.1# ls /etc/*releas*
/etc/amazon-linux-release  /etc/amazon-linux-release-cpe  /etc/os-release  /etc/system-release  /etc/system-release-cpe
bash-5.1#

Success!

**Comment by crramirez** [comment]
Excellent @jgmarce 

Probably I'll write a blog post including the sum of steps.
