### ISSUE TITLE
[Bug] Unable to set FISH Shell as default shell [Fedora Remix for WSL (SystemD)]

### ISSUE THREAD

**Issue by Soromeister** [WhitewaterFoundry/Fedora-Remix-for-WSL#172]
**Note**

These WSL error messages occur from time to time and can tricky to troubleshoot short of reinstalling WSL.

They are usually not an issue with WLinux itself but a glitch with the underlying Windows Subsystem for Linux in Windows 10.

You can help us help you and Microsoft improve WSL and address these if you can provide us some debugging information.

[ ] I have read the above statement.

**Basic Troubleshooting**

Please check:

[x] I have confirmed WSL is enabled: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[x] I have searched Google for the error message.
[x] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[x] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
[ ] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
[ ] I have disabled and re-enabled WSL in Windows Features.
[x] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted to date?

Step 1: Install fish shell and util-linux-user
Step 2: Set fish as default shell with `chsh -s $(which fish)`
Step 3: Open a new tab with the profile `Fedora Remix for WSL (SystemD)`
Step 4: Stare at the error message

**Error Code**

Insert here:  0x00000000

Please check:

[x] This error code is not one listed below.

Known Error Codes
0x80040306 Fix: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#error-0x80040306-on-installation
0x80040154 Fix: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#error-0x80040154-after-windows-update

**Version**

Find: Settings->Apps->Apps & features->WLinux->Advanced Options->Version.

Insert here: 36.0.4.0

**Screenshot**

Insert here: 
![image](https://user-images.githubusercontent.com/45243695/191005088-e2675c22-039f-4712-b1e3-868f8a79c195.png)

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:
OS Name:                   Microsoft Windows 11 Pro for Workstations
OS Version:                10.0.22621 N/A Build 22621
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              Dell Inc. 1.22.0, 2022-08-12

For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**WSL Debug Data**

Please collect and attach .etl files by following this guide: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#starting-bash-gives-an-error-code

**Comment by crramirez** [comment]
Good finding, Thank you for reporting.

**Comment by crramirez** [comment]
Fixed! Just run `update.sh` and it will behave right with fish
