### ISSUE TITLE
[Bug] .hushlogin won't hush the "Systemd is ready." message

### ISSUE THREAD

**Issue by Soromeister** [WhitewaterFoundry/Fedora-Remix-for-WSL#173]
**Describe the bug**
Creating a `.hushlogin` won't disable the startup message `Systemd is ready.`

**To Reproduce**
1. Execute a `$ touch ~/.hushlogin`
2. Open `Fedora Remix for WSL (SystemD)` in a new tab
3. See message that shouldn't be there.

**Expected behavior**
No login messages should be shown when a `~/.hushlogin` is present

**Screenshots**
Ticket is self-explanatory. No need for screenshot

**Additional context**
N/A

**Basic Troubleshooting Checklist**

[x] I have searched Google for the error message.
[x] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[x] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[x] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
[ ] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
[ ] I have disabled and re-enabled WSL in Windows Features.
[x] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here:

**WLinux Version**

Find: Settings->Apps->Apps & features->WLinux->Advanced Options->Version.

Insert here: 36.0.4.0

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:
OS Name:                   Microsoft Windows 11 Pro for Workstations
OS Version:                10.0.22621 N/A Build 22621
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              Dell Inc. 1.22.0, 2022-08-12

For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**Comment by crramirez** [comment]
Good finding, Thank you for reporting.

**Comment by crramirez** [comment]
What needs to be done is to check for the presence of the file `~/.hushlogin` in this script: https://github.com/WhitewaterFoundry/fedora-remix-rootfs-build/blob/6d5fe16ed5577e45a140219ae4e8d43f92862b86/linux_files/start-systemd.sh#L47

If you are participating in hacktoberfest this is a good one. Create a PR in the project https://github.com/WhitewaterFoundry/fedora-remix-rootfs-build

**Comment by Soromeister** [comment]
Thanks for the invitation, @crramirez. I present you my PR: https://github.com/WhitewaterFoundry/fedora-remix-rootfs-build/pull/23

Kindly link the PR to this issue so it gets closed automatically when merged.

**Comment by crramirez** [comment]
Hello @Soromeister ,

Thanks for the contribution. The PR was merged, and you can upgrade the script via `update.sh`

Best Regards,
Carlos

**Comment by Soromeister** [comment]
Thanks for merging.
