### ISSUE TITLE
Trying to add `dnf` repositories fails, saying there is no `epel-38-x86_64` package

### ISSUE THREAD

**Issue by GavinRay97** [WhitewaterFoundry/Fedora-Remix-for-WSL#177]
I've never used Fedora before buying the WhiteWater WSL2 Distro (thanks, I love it, and have adopted it in lieu of Ubuntu!)

So I'm not as familiar with the packaging as I am a lifetime spent with `apt`. When I try to do something like the below:
```sh-session
$ sudo dnf copr enable atim/nushell -y
$ dnf install nushell
```

I get the below error:

```
Repository 'epel-38-x86_64' does not exist in project 'atim/nushell'.
Available repositories: 'fedora-rawhide-x86_64', 'fedora-34-x86_64', 'epel-9-aarch64', 'fedora-35-x86_64', 'centos-stream-9-x86_64', 'fedora-36-x86_64', 'epel-9-x86_64', 'fedora-37-x86_64', 'fedora-rawhide-aarch64', 'centos-stream-9-aarch64', 'epel-8-x86_64', 'fedora-37-aarch64', 'epel-7-x86_64'
```

What is `epel`, and why does it want this?
This is a bit confusing as there seems to be several `fedora` versions available, and even a `rawhide` (which is what I upgraded to).

Thank you =)

**Comment by crramirez** [comment]
Hello @GavinRay97,

Due to Fedora Remix being like a spin-off of Fedora, some tools don't recognize it properly. So, you need to specify to the copr plugin which version you have.

Run this:

```
sudo dnf copr enable atim/nushell -y fedora-rawhide-$(uname -p)
sudo dnf install nushell -y
```

Regards,
Carlos
