### ISSUE TITLE
Exec format error when systemd is enabled

### ISSUE THREAD

**Issue by asgeirn** [WhitewaterFoundry/Fedora-Remix-for-WSL#184]
**Describe the bug**
After updating latest packages yesterday, I am getting `Exec format error` when running Windows executables within WSL2 Fedora.  This worked up until yesterday(ish).

**To Reproduce**
1. Edit `/etc/wsl.conf`, set `systemd=true` in `[boot]`
2. Close  all WSL windows, run `wsl --shutdown` in PowerShell / CMD window
3. Open new Fedora Remix window, run  `explorer.exe`

**Expected behavior**
Explorer window should open

**Additional context**
After disabling systemd, running Windows executables work just fine.

**Basic Troubleshooting Checklist**

- [x] I have searched Google for the error message.
- [x] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
- [x] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
- [x] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
- [ ] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
- [ ] I have disabled and re-enabled WSL in Windows Features.
- [ ] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here:

Disabling systemd.  Also found information here regarding a binfmt.d entry that might work, but the link to the workaround is currently broken: https://github.com/microsoft/WSL/issues/8843

**WLinux Version**

Find: Settings->Apps->Apps & features->WLinux->Advanced Options->Version.

Insert here: 1.0.3.0

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:

```
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19045 N/A Build 19045
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
```

For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**Comment by asgeirn** [comment]
Seems this was a glitch, cannot reproduce after restarting with systemd enabled again..

**Comment by crramirez** [comment]
I have seen this error before when the interop between WSL and Windows is broken. You can solve it with a `wsl --shutdown`, but sometimes you need a restart. The store version of WSL is not quite stable, and these errors happen. 

Also, sometimes it freezes, and the `wsl` command stops responding, in that case, you need to go to Task Manager and kill the **Windows Subsystem for Linux** processes and `wsl --shutdown` until it restarts.
