### ISSUE TITLE
Unable to install Remi's RPM repo

### ISSUE THREAD

**Issue by beganovich** [WhitewaterFoundry/Fedora-Remix-for-WSL#187]
**Describe the bug**
Unable to install Remi's RPM repo.

**To Reproduce**

1. Fully update the 37
2. Run the following command:

```bash
sudo dnf install https://rpms.remirepo.net/fedora/remi-release-37.rpm
```

**Expected behavior**
To successfully add the RPM.

**Basic Troubleshooting Checklist**

[x] I have searched Google for the error message.
[x] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[x] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[x] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
[x] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
[x] I have disabled and re-enabled WSL in Windows Features.
[x] I have run Windows 10 updates and restarted.

**Fedora Remix for WSL Version**

Find: Settings->Apps->Apps & features->Fedora Remix for WSL Version->Advanced Options->Version.
Also, `cat /etc/os-release`

Insert here:

```bash
benjamin@DESKTOP-O32UVE7 ~> cat /etc/os-release
NAME="Fedora Remix for WSL"
VERSION="37"
ID=fedoraremixforwsl
ID_LIKE=fedora
VERSION_ID=37
PLATFORM_ID="platform:f37"
PRETTY_NAME="Fedora Remix for WSL"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:37"
HOME_URL="https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL"
SUPPORT_URL="https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL"
BUG_REPORT_URL="https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL/issues"
PRIVACY_POLICY_URL="https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL/blob/master/PRIVACY.md"
FEDORA_REMIX_VERSION=37.0.4
```

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:

```powershell
OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.19045 N/A Build 19045
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              HP T70 Ver. 01.11.01, 12/2/2022
```

For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**Comment by crramirez** [comment]
Hello @beganovich 

Use:

```bash
sudo dnf install --allowerasing https://rpms.remirepo.net/fedora/remi-release-37.rpm
```

This repo is designed to only install in Fedora mainstream and not in any Fedora Remix, as it has the fedora-release package as a hard dependency.

The above command will remove the generic-release package and install the fedora-release only, converting the Fedora Remix into Fedora. You should not experience any issues, but I recommend you back up your distro before doing that.

Regards,
Carlos

**Comment by beganovich** [comment]
That seems to be working, thanks 👍
