### ISSUE TITLE
possible bug in upgrade.sh ?

### ISSUE THREAD

**Issue by nuitlejour** [WhitewaterFoundry/Fedora-Remix-for-WSL#189]
My fedora remix version is 37.

I am using the latest upgrade.sh from the main branch, the following statements from update.sh:62

curl -s https://packagecloud.io/install/repositories/whitewaterfoundry/fedoraremix/script.rpm.sh | sudo env os=fedora dist=37 bash

yields error:
Installing pygpgme to verify GPG signatures...
whitewaterfoundry_fedoraremix-source                                                    145  B/s | 833  B     00:05
No match for argument: pygpgme
Error: Unable to find a match: pygpgme

It could be an error, please check.

**Comment by crramirez** [comment]
Hello @nuitlejour

This is the script that installs the repo that we have in packagecloud, it is a bit verbose. It works despite this error. Also, we must leave this as is because the GPG verification in WSL1 is broken for dnf

Thanks for reporting
