### ISSUE TITLE
Port arm64 fedora using WSA backend

### ISSUE THREAD

**Issue by nuitlejour** [WhitewaterFoundry/Fedora-Remix-for-WSL#194]
Windows Subsystem for Android™️ (WSA) is able to emulate arm64 hardware and running android operating system on it, is it possible to port arm64 fedora system (or any flavor of linux) using wsa backend?

possible solution (??) can be found:
https://github.com/LSPosed/MagiskOnWSALocal

**Comment by nuitlejour** [comment]
I am sorry, it seams that the android within WSA is actually x86_64...

**Comment by crramirez** [comment]
Hello @nuitlejour 

Which is your use case? 

Do you want to run the distro in a Windows Arm64?
Do you want to run ARM software inside WSL on Windows x86_64?

I can give you options

Regards,
Carlos

**Comment by nuitlejour** [comment]
@crramirez thank you for your attention!
I am trying to build arm64 linux software (mainly arm64 conda environment) on X86_64 windows operating system. 
I have tried qemu, it's complicated and the performance is bad.
Is there any emulation solution with which I can install arm64 linux on X64 system?
thanks again!
