### ISSUE TITLE
Using fish shell breaks ssh ProxyJump

### ISSUE THREAD

**Issue by seowalex** [WhitewaterFoundry/Fedora-Remix-for-WSL#195]
**Describe the bug**
I am facing the exact same problem as WhiteWaterFoundry/Pengwin/issues/712 which was solved for that distro in WhitewaterFoundry/pengwin-base/pull/119. Could a similar fix be made for this distro?

**Basic Troubleshooting Checklist**

- [x] I have searched Google for the error message.
- [x] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
- [x] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
- [x] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
- [ ] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
- [ ] I have disabled and re-enabled WSL in Windows Features.
- [x] I have run Windows 10 updates and restarted.

**Fedora Remix for WSL Version**

37.1.2

**Windows Build**

10.0.22000 N/A Build 22000

**Comment by seowalex** [comment]
Any progress on this?

**Comment by crramirez** [comment]
Hello @seowalex,

Sorry for the delayed response, please run the `update.sh` script and see if the problem was solved.

Regards,
Carlos

**Comment by seowalex** [comment]
Yes, that seems to work.
