### ISSUE TITLE
wsl: Nested virtualization is not supported on this machine.

### ISSUE THREAD

**Issue by SynapseScribe** [WhitewaterFoundry/Fedora-Remix-for-WSL#200]
**Note**

These WSL error messages occur from time to time and can tricky to troubleshoot short of reinstalling WSL.

They are usually not an issue with WLinux itself but a glitch with the underlying Windows Subsystem for Linux in Windows 10.

You can help us help you and Microsoft improve WSL and address these if you can provide us some debugging information.

[ ] I have read the above statement.

**Basic Troubleshooting**

Please check:

[ ] I have confirmed WSL is enabled: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[ ] I have searched Google for the error message.
[ ] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[ ] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
[ ] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
[ ] I have disabled and re-enabled WSL in Windows Features.
[ ] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted to date?

**Error Code**

Insert here:

Please check:

[ ] This error code is not one listed below.

Known Error Codes
0x80040306 Fix: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#error-0x80040306-on-installation
0x80040154 Fix: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#error-0x80040154-after-windows-update

**Version**

Find: Settings->Apps->Apps & features->WLinux->Advanced Options->Version.

Insert here:

**Screenshot**

Insert here:

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:

For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**WSL Debug Data**

Please collect and attach .etl files by following this guide: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#starting-bash-gives-an-error-code

**Comment by crramirez** [comment]
Hello,

It is not the distro it is your processor. Do you have an AMD processor with Windows 10?

The warning is only shown on the first distro that you launch. You can get rid of this warning disabling the nested virtualization on WSL with:

```bash
echo -e "\n[wsl2]\nnestedVirtualization=false\n" >>winhome/.wslconfig
```

Regards,
Carlos

**Comment by crramirez** [comment]
When you see the warning is because is not working. But I don't know why it isn't working with the VMware Workstation
