### ISSUE TITLE
Fedora 39 release

### ISSUE THREAD

**Issue by nlogozzo** [WhitewaterFoundry/Fedora-Remix-for-WSL#207]

**Comment by crramirez** [comment]
Hello,

We apologize for the delay; we had many issues with the Mesa build that forced us to downgrade it and ship Fedora 39 with mesa 23.1 instead of 23.2.

The release is on its way.

**Comment by nlogozzo** [comment]
https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL/releases/tag/39.0.0

**Comment by crramirez** [comment]
https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL/releases/tag/39.0.1
