### ISSUE TITLE
README badge broken

### ISSUE THREAD

**Issue by wheeheee** [WhitewaterFoundry/Fedora-Remix-for-WSL#218]
**Describe the bug**
The link to the image for the badge is broken, see the README page.
Easily fixed by generating code for the badge with https://apps.microsoft.com/badge.

**To Reproduce**
Go to https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL, look at readme.

**Expected behavior**
Nice Microsoft Store badge.

**Screenshots**
nopes

**Additional context**
NA

**Basic Troubleshooting Checklist**

[✅] I have searched Google for the error message.
[✅] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[✅] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[✅] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
[✅] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
[✅] I have disabled and re-enabled WSL in Windows Features.
[✅] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here:
NA

**Fedora Remix for WSL Version**

Find: Settings->Apps->Apps & features->Fedora Remix for WSL Version->Advanced Options->Version.
Also, `cat /etc/os-release`

Insert here:
NA

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:

NA

For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**Comment by crramirez** [comment]
Thanks for reporting it
