### ISSUE TITLE
Don't modify /etc/profile directly

### ISSUE THREAD

**Issue by rathann** [WhitewaterFoundry/Fedora-Remix-for-WSL#22]
**Is your feature request related to a problem? Please describe.**
`/etc/profile` should not be modified without rebuilding the setup package. `rpm -V setup` will show it's been modified and subsequent upgrades will create `/etc/profile.rpmnew`.

**Describe the solution you'd like**
Instead of modifying `/etc/profile` directly, you can drop a `.sh` (e.g. `wsl.sh`) file in `/etc/profile.d` with the contents you want. See line 65 of unmodified `/etc/profile`.

**Comment by sirredbeard** [comment]
Something like this? #23

**Comment by rathann** [comment]
Yes, much better. Thank you.
