### ISSUE TITLE
KDE Session

### ISSUE THREAD

**Issue by RokeJulianLockhart** [WhitewaterFoundry/Fedora-Remix-for-WSL#223]
**Is your feature request related to a problem? Please describe.**

Like https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL/issues/82#issue-637918634 requests, I want to use a KDE session. I don't see any information in https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL/blob/217fc1ad66a0107548f79c1ba3b37745d478fbd5/README.md#fedora-remix-for-windows-subsystem-for-linux-wsl about how to accomplish this.

**Describe the solution you'd like**

Provide a KDE session and documentation of how to utilize it.

**Describe alternatives you've considered**

Manual installation of https://download.fedoraproject.org/pub/fedora/linux/releases/40/Spins/x86_64/iso/Fedora-KDE-Live-x86_64-40-1.14.iso from https://fedoraproject.org/spins/kde/download somehow (I suppose like https://github.com/MicrosoftDocs/WSL/blob/b882fb4ac43b2ceae34f5c8b082a9f03178d443b/WSL/install.md#change-the-default-linux-distribution-installed describes, per https://discussion.fedoraproject.org/t/how-to-install-fedora-in-wsl-for-windows/75753/10).

**Additional context**

https://plethora.debian.net/viewtopic.php?p=734333&sid=57fccad92fd1203faa629ec83707564d#p734333:~:text=The%20following%20link%20has%20a%20batch%20file%20for%20KDE%2C%20but%20it%20is%20for%20the%20Fedora%20distribution:%20Windows%2010%20+%20WSL2%20+%20Fedora%20Remix%20+%20KDE%20+%20X410 is the sole place that I have even seen this discussed.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL/issues/223#issue-2386766548

I didn't notice https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL/commit/ba39b980132285f5ecdf55f494fcd1569d3e1b38#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR2.

**Comment by crramirez** [comment]
Well we need to add it to the Readme
