### ISSUE TITLE
No copr wslutilities/wslu repo for Fedora 41

### ISSUE THREAD

**Issue by magikmw** [WhitewaterFoundry/Fedora-Remix-for-WSL#228]
**Describe the bug**
After updating to F41 we're greeted with a 404 error by DNF explaining that it cannot find wslutilities/wslu copr repodata/repomd.xml
And no wonder, as the repo for F41 doesn't exist.

**To Reproduce**
1. Update to F41 (I've used F39-F40 update guide bumping the version in commands)
2. run `dnf update`

**Expected behavior**
Repo exists, we get packages.

**Screenshots**
n/a

**Additional context**
This is fairly obviously an upstream problem, but it affects this product, hence the report.
I'm not entirely sure what Fedora-Remix-for-WSL uses wslu for, but I believe the response is on maintainers.

**Basic Troubleshooting Checklist**

[x] I have searched Google for the error message.
[x] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[x] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[x] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
[x] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
[x] I have disabled and re-enabled WSL in Windows Features.
[x] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here:

I've tried looking for the copr repo https://copr.fedorainfracloud.org/coprs/wslutilities/wslu/

**Fedora Remix for WSL Version**

Find: Settings->Apps->Apps & features->Fedora Remix for WSL Version->Advanced Options->Version.
Also, `cat /etc/os-release`

Insert here:

```
NAME="Fedora Remix for WSL"
VERSION="41"
ID=fedoraremixforwsl
ID_LIKE=fedora
VERSION_ID=41
PLATFORM_ID="platform:f41"
PRETTY_NAME="Fedora Remix for WSL"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:41"
HOME_URL="https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL"
SUPPORT_URL="https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL"
BUG_REPORT_URL="https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL/issues"
PRIVACY_POLICY_URL="https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL/blob/master/PRIVACY.md"
FEDORA_REMIX_VERSION=41.0.0
```

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:

```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19045 N/A Build 19045
```

For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**Comment by crramirez** [comment]
Hello @magikmw

Thanks for reporting. This repo takes time to. Be updated so we use the previous version one until it gets updated. I'll include this fix in the update.sh script.

Regards,
Carlos

**Comment by crramirez** [comment]
The COPR is now there

**Comment by mattgagliardi** [comment]
@crramirez FWIW same issue has cropped up again with the Fedora 42 update. I commented in the blog post/release announcement.

**Comment by crramirez** [comment]
Hello @mattgagliardi ,

We appreciate the feedback.  Unfortunately, the project's maintainer recently ceased development and archived it.  We will, however, incorporate it into our repositories and adapt the associated script.  This project remains highly valuable and will continue to be supported in our distributions.

Best
