### ISSUE TITLE
Unable to upgrade version 1.0.26 to 1.0.28

### ISSUE THREAD

**Issue by cronhan** [WhitewaterFoundry/Fedora-Remix-for-WSL#35]
Hi, 

My actual issue is #5 (which I only encountered today), and apparently the fix for that is to upgrade (although I started out with 1.0.26 which supposedly already has a fix). However I am getting an error when trying to update (using the Github image):

(Translated from original, so not verbatim): Ask the developer for a new package. This one can conflict with an already installed package or it depends on things that are not installed or is made for another architecture. 0x80073CF3 

Double checked that I downloaded the x64 version. Any ideas?

**Comment by kubajar** [comment]
Similar issue for me, DistroLauncher-Appx_1.0.28.0_x64_arm64.appxbundle helped. :-)

**Comment by cronhan** [comment]
Okay, thanks for that, I did not realize that the version I installed initially was the "combined" version.
