### ISSUE TITLE
[Release 30] Install glibc-langpack-en

### ISSUE THREAD

**Issue by xasx** [WhitewaterFoundry/Fedora-Remix-for-WSL#38]
**Describe the bug**
WSL sets the default locale to en_US.UTF-8.
However, the corresponding langpack is not installed, so `locale` complains about missing files or shells like fish do not render many glyphs at all.

**To Reproduce**
1. Install FedoraRemix 30
2. Once set up, run locale
3. Or install fish and bobthefish theme
4. See many questionmarks instead of UTF8 glyphs

**Expected behavior**
Characters are displayed correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/1582730/58136054-f4dc6300-7c2c-11e9-9965-6d4c8ed28946.png)
See first installed, then removed, replaced fish and ran `locale`.

Insert here:

**WLinux Version 30**

**Comment by sirredbeard** [comment]
Added here: https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL/pull/39

Will test for Fedora 30 release.
