### ISSUE TITLE
Upgrade to Fedora 31

### ISSUE THREAD

**Issue by WSLUser** [WhitewaterFoundry/Fedora-Remix-for-WSL#51]
**Is your feature request related to a problem? Please describe.**
Image is not up to date
**Describe the solution you'd like**
Update Store Image
**Describe alternatives you've considered**
Dnf can be used instead.
**Additional context**
Updating the image should also update already installed images.

**Comment by JackTheFlap** [comment]
You can use the following page to upgrade to Fedora 31:
https://fedoramagazine.org/upgrading-fedora-30-to-fedora-31/

I had to use the --allowerasing and --skip-broken to bypass two Errors:
1. generic-release-common-30-0.3.noarch
2. generic-release-30-0.3.noarch

Both had the following errors:
Error:
 Problem 1: problem with installed package generic-release-common-30-0.3.noarch
  - package generic-release-common-30-0.3.noarch requires fedora-repos(30), but none of the providers can be installed    
  - fedora-repos-30-2.noarch does not belong to a distupgrade repository
 Problem 2: problem with installed package generic-release-30-0.3.noarch
  - package generic-release-30-0.3.noarch requires generic-release-common = 30-0.3, but none of the providers can be installed
  - package generic-release-common-30-0.3.noarch requires fedora-repos(30), but none of the providers can be installed
  - package fedora-repos-30-2.noarch requires fedora-gpg-keys = 30-2, but none of the providers can be installed 
  - fedora-gpg-keys-30-2.noarch does not belong to a distupgrade repository

I was able to upgrade my work instance with no issues but on my home PC when running 'dnf system-upgrade reboot' It gives me the error: 'Error: system is not ready for upgrade'

I've tried restarting Terminal, manually killing the WSL service through task manger and restarting Windows, all give the same message.

**Comment by crramirez** [comment]
Hello Jack,

Use this command instead:

sudo dnf system-upgrade upgrade

We are working in upgrade the base image. But we can include for now the steps to do an in place upgrade. 

Regards

**Comment by crramirez** [comment]
Here the compiled instructions:

https://www.pengwin.dev/blog/2019/11/3/upgrade-fedora-remix-for-wsl-to-31

**Comment by crramirez** [comment]
An update, we cannot release until this issue is fixed:

https://bugzilla.redhat.com/show_bug.cgi?id=1753716
