### ISSUE TITLE
DB_VERSION_MISMATCH when attempting to manage packages

### ISSUE THREAD

**Issue by 0xADD1E** [WhitewaterFoundry/Fedora-Remix-for-WSL#53]
**Describe the bug**
When attempting to install a package:
```
error: db5 error(-30969) from dbenv->open: BDB0091 DB_VERSION_MISMATCH: Database environment version mismatch
error: cannot open Packages index using db5 -  (-30969)
error: cannot open Packages database in /var/lib/rpm
```

**To Reproduce**

Unknown. I haven't been doing anything abnormal, so far as I know. 

I also encountered this when attempting to upgrade from 30 to 31, but I opted to fix that by completely reinstalling the application. I would really rather not do that here.

**Basic Troubleshooting Checklist**

- [x] I have searched Google for the error message.
- [x] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
- [x] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
- [x] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
- [ ] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
- [ ] I have disabled and re-enabled WSL in Windows Features.
- [ ] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

```
# rpmdb --rebuilddb
error: failed to replace old database with new database!
error: replace files in /var/lib/rpm with files from /var/lib/rpmrebuilddb.1330 to recover
```

**WLinux Version**

1.31.5.0

**Windows Build**

 10.0.18362

**Comment by crramirez** [comment]
Hello @0xADD1E 

Try this 

```
sudo dnf upgrade --refresh rpm glibc
sudo rm /var/lib/rpm/.rpm.lock
sudo dnf upgrade dnf
```

Regards

**Comment by modzilla99** [comment]
Thanks! That resolves that issue!

**Comment by 0xADD1E** [comment]
```
# dnf upgrade --refresh rpm glibc
...
Dependencies resolved.
Nothing to do.
Complete!

# rm /var/lib/rpm/.rpm.lock
# dnf upgrade dnf
...
Dependencies resolved.
Nothing to do.
Complete!
```

And then, attempting to install a new package succeeds. Was it really just the lockfile? or did the dnf commands do something that they're not mentioning?

If the former, do you think there's a case for this being an upstream issue with rpm's error messages?

**Comment by 0xADD1E** [comment]
In either case, thank you for your help!

**Comment by barnscott** [comment]
Just for reference, I just encountered this same issue. Had not had issue since I installed FedoraRemix on this PC in Oct 2019.
I updated my PC to 2004, upgraded to release 32, and issue began. Not sure exactly what caused it, but the same resolution fixed it.

**Comment by crramirez** [comment]
This error is really erratic, this happened to me once. We don't know how to reproduce it or which is the cause. We create a script called upgrade.sh that takes care of it. Just run it every time that you can call dnf update or very time when you see this error.

Regards

**Comment by astronomerdave** [comment]
Did not fix the problem on CentOS Linux release 8.5.2111. After following @crramirez 's suggestion, still have the following:
```
RPM: error: db5 error(-30969) from dbenv->open: BDB0091 DB_VERSION_MISMATCH: Database environment version mismatch
RPM: error: cannot open Packages index using db5 -  (-30969)
RPM: error: cannot open Packages database in /var/lib/rpm

**Comment by sereneshikari** [comment]
`rpmdb --rebuilddb` worked for me too, thanks! I didn't have to use `sudo` since I was already running as `root`

**Comment by NovqiGarrix** [comment]
`rpmdb --rebuilddb` also works for me. Nice!
