### ISSUE TITLE
Appxbundle certificate expired on 2019-12-09

### ISSUE THREAD

**Issue by ChristianStadelmann** [WhitewaterFoundry/Fedora-Remix-for-WSL#55]
**Describe the bug**
Cannot install the appxbundle because the certificate expired just a few hours ago.

**To Reproduce**
1. Follow the steps on https://docs.microsoft.com/en-us/windows/wsl/install-win10 to enable WSL.
2. Download the "1.31.6 Final" build from https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL/releases
3. In a powershell, run `Add-AppxPackage .\DistroLauncher-Appx_1.31.6.0_x64.appxbundle`
4. look at powershell output

**Expected behavior**
Install Fedora Remix WSL image

**Error message**
```
> Add-AppxPackage .\DistroLauncher-Appx_1.31.6.0_x64.appxbundle
Add-AppxPackage : Fehler bei Bereitstellung. HRESULT: 0x800B0101, Ein erforderliches Zertifikat befindet sich nicht im
Gültigkeitszeitraum gemessen an der aktuellen Systemzeit oder dem Zeitstempel in der signierten Datei.
Fehler 0x800B0101: Fehler beim Öffnen des Pakets im Speicherort "DistroLauncher-Appx_1.31.6.0_x64.appxbundle".
HINWEIS: Wenn Sie weitere Informationen wünschen, suchen Sie im Ereignisprotokoll nach [ActivityId]
1182c42d-ae9c-0002-c4db-8b119caed501, oder verwenden Sie die Befehlszeile Get-AppxLog -ActivityID
1182c42d-ae9c-0002-c4db-8b119caed501
In Zeile:1 Zeichen:1
+ Add-AppxPackage .\DistroLauncher-Appx_1.31.6.0_x64.appxbundle
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Users\AU0001..._x64.appxbundle:String) [Add-AppxPackage], Exception
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand
```

Basic error message means that the certificate has expired.

**Additional context**
You can verify that the certificate has expired by following these steps:
1. Find the .appxbundle file in your Windows explorer
2. right-click, open properties
3. Switch to tab "Digital Signatures"
4. Select signature from the list and click "Details"
5. Click "View Certificate"
6. Switch to tab "Details"

There you will see that the "valid until" date is 2019-12-11 00:59:59, which is already in the past at the time of writing.

**Basic Troubleshooting Checklist**

[x] I have searched Google for the error message.
[x] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[x] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[x] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
[no] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
[no] I have disabled and re-enabled WSL in Windows Features.
[x] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

None but the above.

**WLinux Version**

not applicable because I could not install it.

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:

Note: This command only returns my BIOS version which you are probably not interested in ;)

Not relevant for the issue.

**Comment by crramirez** [comment]
Hello,

Thank you for reporting. We have had problems in renewing our certificate. I will update this issue when we had the newer and updated the package. 

Regards, 
Carlos

**Comment by ChristianStadelmann** [comment]
Thank you for your answer!

**Comment by lukearndt** [comment]
I had the same issue, and you helped me understand what was wrong. Thank you for reporting it so clearly - you saved me a lot of time!

As a temporary workaround, you could try changing your Windows system date to before the certificate expired. Doing that allowed me to install it on my system.

I returned the date back to normal after installing, and it continues to work. The earlier date just helped it pass the certificate check for the installer package.

**Comment by staticinvocation** [comment]
In the future, please consider timestamping releases (it prevents the signature from expiring when the cert expires).

**Comment by crramirez** [comment]
We generated a new package and also timestamped: https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL/releases/tag/1.31.10

**Comment by AlexDyukov** [comment]
@crramirez could you provide link for new version of uwpdesktop we should use, because of microsoft help link: https://www.microsoft.com/en-us/download/details.aspx?id=53175
has lower version and i cannot install package manual:
```
PS C:\Users\Aleksandr.Dyukov\Downloads> Add-AppPackage .\Fedora-Remix-for-WSL_1.31.10.0_x64_arm64.appxbundle
Add-AppPackage : Deployment failed with HRESULT: 0x80073CF3, Package failed updates, dependency or conflict validation.
Windows cannot install package WhitewaterFoundryLtd.Co.FedoraRemixforWSL_1.31.10.0_x64__zxdhfybd17krt because this package depends on a framework that could not be found.
 Provide the framework "Microsoft.VCLibs.140.00.UWPDesktop" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral
or x64 processor architecture and minimum version 14.0.27323.0, along with this package to install. The frameworks with name "Microsoft.VCLibs.140.00.UWPDesktop" currentl
y
Windows cannot install package WhitewaterFoundryLtd.Co.FedoraRemixforWSL_1.31.10.0_x64__zxdhfybd17krt because this package depends on a framework that could not be found.
 Provide the framework "Microsoft.VCLibs.140.00.UWPDesktop" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral
or x64 processor architecture and minimum version 14.0.27323.0, along with this package to install. The frameworks with name "Microsoft.VCLibs.140.00.UWPDesktop" currentl
y installed are: {}
NOTE: For additional information, look for [ActivityId] 5bec70ba-bb37-0004-0e98-ee5b37bbd501 in the Event Log or use the command line Get-AppPackageLog -ActivityID 5bec70
ba-bb37-0004-0e98-ee5b37bbd501
At line:1 char:1
+ Add-AppPackage .\Fedora-Remix-for-WSL_1.31.10.0_x64_arm64.appxbundle
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\Aleksa...rm64.appxbundle:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

PS C:\Users\Aleksandr.Dyukov\Downloads> Get-ItemProperty -Path .\vc_uwpdesktop.140.exe | Format-list -Property * -Force |findstr -i version
VersionInfo       : File:             C:\Users\Aleksandr.Dyukov\Downloads\vc_uwpdesktop.140.exe
                    FileVersion:      14.0.24222.0
                    FileDescription:  Microsoft Visual C++ 140 UWP Desktop Conversion Extension - 14.0.24217.00
                    Product:          Microsoft Visual C++ 140 UWP Desktop Conversion Extension - 14.0.24217.00
                    ProductVersion:   14.0.24222.0
```

**Comment by crramirez** [comment]
Thanks, I will look for it, or try to reduce the version dependency.

**Comment by crramirez** [comment]
A new release was published lowering the requirements

**Comment by AlexDyukov** [comment]
@crramirez as i can see the requirements lowered, but i am getting error with "developer licence required" which i cannot parse because of low windows experience. Looks like package OK now and its all about my own problem
```
PS C:\Users\Aleksandr.Dyukov\Downloads> Add-AppPackage "C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.VCLibs.Desktop\14.0\Appx\Retail\x64\M
icrosoft.VCLibs.x64.14.00.Desktop.appx"
PS C:\Users\Aleksandr.Dyukov\Downloads> Add-AppPackage .\Fedora-Remix-for-WSL_1.31.14.0_x64_arm64.appxbundle
Add-AppPackage : Deployment failed with HRESULT: 0x80073CFF, To install this application you need either a Windows developer license or a sideloading-enabled system.
Deployment of package WhitewaterFoundryLtd.Co.FedoraRemixforWSL_1.31.14.0_neutral_split.scale-125_zxdhfybd17krt with package origin Unknown failed because no valid licens
e or sideloading policy could be applied. A developer license (http://go.microsoft.com/fwlink/?LinkId=233074) or enterprise sideloading configuration (http://go.microsoft
.com/fwlink/?LinkId=231020) may be required.
NOTE: For additional information, look for [ActivityId] 5bec70ba-bb37-0004-99d9-f25b37bbd501 in the Event Log or use the command line Get-AppPackageLog -ActivityID 5bec70
ba-bb37-0004-99d9-f25b37bbd501
At line:1 char:1
+ Add-AppPackage .\Fedora-Remix-for-WSL_1.31.14.0_x64_arm64.appxbundle
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Users\Aleksa...rm64.appxbundle:String) [Add-AppxPackage], Exception
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

PS C:\Users\Aleksandr.Dyukov\Downloads> Add-AppPackage .\Fedora-Remix-for-WSL_1.31.10.0_x64_arm64.appxbundle
Add-AppPackage : Deployment failed with HRESULT: 0x80073CF3, Package failed updates, dependency or conflict validation.
Windows cannot install package WhitewaterFoundryLtd.Co.FedoraRemixforWSL_1.31.10.0_x64__zxdhfybd17krt because this package depends on a framework that could not be found.
 Provide the framework "Microsoft.VCLibs.140.00.UWPDesktop" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral
or x64 processor architecture and minimum version 14.0.27323.0, along with this package to install. The frameworks with name "Microsoft.VCLibs.140.00.UWPDesktop" currentl
y
Windows cannot install package WhitewaterFoundryLtd.Co.FedoraRemixforWSL_1.31.10.0_x64__zxdhfybd17krt because this package depends on a framework that could not be found.
 Provide the framework "Microsoft.VCLibs.140.00.UWPDesktop" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral
or x64 processor architecture and minimum version 14.0.27323.0, along with this package to install. The frameworks with name "Microsoft.VCLibs.140.00.UWPDesktop" currentl
y installed are: {Microsoft.VCLibs.140.00.UWPDesktop_14.0.24217.0_x64__8wekyb3d8bbwe}
NOTE: For additional information, look for [ActivityId] 5bec70ba-bb37-0004-a1d9-f25b37bbd501 in the Event Log or use the command line Get-AppPackageLog -ActivityID 5bec70
ba-bb37-0004-a1d9-f25b37bbd501
At line:1 char:1
+ Add-AppPackage .\Fedora-Remix-for-WSL_1.31.10.0_x64_arm64.appxbundle
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\Aleksa...rm64.appxbundle:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand
```

**Comment by BadNetCode** [comment]
@AlexDyukov I'm having the same problem. Did you resolve it?

**Comment by crramirez** [comment]
![image](https://user-images.githubusercontent.com/8397379/72385021-e5131100-371e-11ea-9c4c-68b5dc0c1ad8.png)

**Comment by AlexDyukov** [comment]
@BadNetCode sorry, backlogged my task for Fedora in WSL. I has low windows experience to debug it. Ubuntu 18.04 / 16.04 from https://docs.microsoft.com/en-us/windows/wsl/install-manual works well
 
@crramirez security policy does not allow it (enterprise environment) and there is no checkbox you are link:
![Untitled](https://user-images.githubusercontent.com/21895986/72441911-8b612400-37bc-11ea-93e4-1a465b127ee5.png)

**Comment by crramirez** [comment]
Click on Sideload apps

**Comment by AlexDyukov** [comment]
@crramirez agree, thats works fine now. Asked my co-workers to reproduce install, so we can close issue with this solution

**Comment by AlexDyukov** [comment]
Okey, we had reproduce install on several mashines. Its works good. At least it requires install UWP:
1) download UWP package from https://www.microsoft.com/en-us/download/details.aspx?id=53175
2) then install it through executing "exe" file
2) then install it like appx package:
```
Add-AppPackage "C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.VCLibs.Desktop\14.0\Appx\Retail\x64\M
icrosoft.VCLibs.x64.14.00.Desktop.appx"
```

Dunno hows third step affects UWP, but it doesnt work with out it.

@BadNetCode any success?

**Comment by ChristianStadelmann** [comment]
Thank you for fixing this issue!
