### ISSUE TITLE
Fedora Remix Build Problem 2 : Package generic-release

### ISSUE THREAD

**Issue by alexismaret1test** [WhitewaterFoundry/Fedora-Remix-for-WSL#57]
**Describe the bug**
The file "create-targz.sh" that permit to create the "install.tar.gz" produces error:
`
No match for argument: generic-release
Error: Unable to find a match
`
It is caused by the line 47 : 
`dnf -y install generic-release --allowerasing`

**To Reproduce**
Steps to reproduce the behavior: Just follow the guide to build Fedoraremix Distribution (as Pengwin)
1. Go on a real Fedora
2. sudo sh create-targz.sh
3. Error occured :
 `No match for argument: generic-release
Error: Unable to find a match`

**Expected behavior**
I expect the script to be usable under fedora and to work without any errors.
The script must build the file "install.tar.gz" in the architecture folder chosen.

**Workaround**
I searched for a package named "generic-release"
`dnf list generic-release`
`Last metadata expiration check: 0:00:39 ago on Wed 18 Dec 2019 11:48:28 AM CET.`
`Installed Packages`
`generic-release.noarch                                 29-1.fc29                                 @updates`

So i modify the script to change name of the package to "generic-release.noarch"
line 47: `dnf -y install generic-release.noarch --allowerasing`

But still got the same error
`No match for argument: generic-release.noarch
Error: Unable to find a match`

So i comment the line 47 since it is already installed on my system.
`#dnf -y install generic-release.noarch --allowerasing`

**Additional context**
Fedora Version 29
`cat /etc/fedora-release 
Generic release 29 (Generic)
`

I have found similar errors in this script so i posted an issue for each build error i encountered

**Comment by ganto** [comment]
Fedora 29 is end-of-life since 2019-11-30 therefore I don't think any Fedora 29 related bugs will ever be fixed.

**Comment by crramirez** [comment]
This error was a nightmare with to upgrade to Fedora 31 but it is fine now
