### ISSUE TITLE
dnf update -> SSL certificate problem @ 1.31.15.0

### ISSUE THREAD

**Issue by difr** [WhitewaterFoundry/Fedora-Remix-for-WSL#70]
**dnf update -v**
Loaded plugins: builddep, changelog, config-manager, copr, debug, debuginfo-install, download, generate_completion_cache, needs-restarting, playground, repoclosure, repodiff, repograph, repomanage, reposync
DNF version: 4.2.18
cachedir: /var/cache/dnf
Unknown configuration value: failovermethod=priority in /etc/yum.repos.d/fedora-updates-modular.repo; Configuration: OptionBinding with id "failovermethod" does not exist
... (2 same errors) ...
User-Agent: constructed: 'libdnf (Fedora Remix for WSL 31; generic; Linux.x86_64)'
repo: downloading from remote: fedora-modular
error: Curl error (60): SSL peer certificate or SSH remote key was not OK for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-31&arch=x86_64 [SSL certificate problem: self signed certificate in certificate chain] (https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-31&arch=x86_64).
... (many same errors) ...
Fedora Modular 31 - x86_64                                                              0.0  B/s |   0  B     00:04
Errors during downloading metadata for repository 'fedora-modular':
  - Curl error (60): SSL peer certificate or SSH remote key was not OK for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-31&arch=x86_64 [SSL certificate problem: self signed certificate in certificate chain]
Error: Failed to download metadata for repo 'fedora-modular': Cannot prepare internal mirrorlist: 

----
at fresh installed "**Fedora-Remix-for-WSL_1.31.15.0_x64_arm64.appxbundle**"
MS Windows 10 Pro, 10.0.18363

**Comment by crramirez** [comment]
Hello,

We will take a look. But it looks like a temporary repository problem.

Regards

**Comment by difr** [comment]
@crramirez 
looks like Kaspersky ativirus is in game.
thank you.
