### ISSUE TITLE
'1.31.19 Final' installation failed with certificate trust error 

### ISSUE THREAD

**Issue by mi-hol** [WhitewaterFoundry/Fedora-Remix-for-WSL#74]
**Describe the bug**
installation failed with certificate trust error 

**To Reproduce**
1. Download [latest version 1.31.19.0](https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL/releases/download/1.31.19/Fedora-Remix-for-WSL_1.31.19.0_x64_arm64.appxbundle)
2. Click on 'Fedora-Remix-for-WSL_1.31.19.0_x64_arm64.appxbundle'
3. See error
"A certificate chain processed, but terminated in a root certificate which isn't trusted (0x800B0109)"

**Expected behavior**
Installation completes successfully

**Screenshots**

**Additional context**
NA
**Basic Troubleshooting Checklist**

[x] I have searched Google for the error message.
[x] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[x ] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[x ] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
[ ] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
[ ] I have disabled and re-enabled WSL in Windows Features.
[ ] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here:

**WLinux Version**

Find: Settings->Apps->Apps & features->WLinux->Advanced Options->Version.

Insert here:
NA
**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:
C:\Users\user>systeminfo | findstr /C:"OS"
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19041 N/A Build 19041
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              Hewlett-Packard 68SCE Ver. F.67, 13.02.2018

For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**Comment by crramirez** [comment]
Hello,

Thanks for reporting we will release a new package shortly.

Regards,
Carlos

**Comment by crramirez** [comment]
Ready: https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL/releases/tag/1.31.21

**Comment by mi-hol** [comment]
Thanks
