### ISSUE TITLE
1st run after "Install" from MSFT Store fails during unpacking

### ISSUE THREAD

**Issue by jamesdavidhoward** [WhitewaterFoundry/Fedora-Remix-for-WSL#78]
Used instructions at `https://docs.microsoft.com/en-us/windows/wsl/install-win10` to enable WSL, enable VM Platform, reboot & set version to WSL2 on my "Insider" (slow ring) build 19041.264 Windows 10 64-bit.  Then visited MSFT Store to find, buy and install "Fedora Remix".  Download completed (after moving default install location to my system drive `C:`), then `[Launch]` from MSFT Store page for Fedora Remix.  Command-line window popped up, and almost immediately died, telling me:

> Unpacking Linux filesystem image, this may take a few minutes...
> `WslRegisterDistribution` failed with error: 0x80370102
> Error: 0x80370102 The virtual machine could not be started because a required feature is not installed.
> 
> Press any key to continue...

It seems the instructions at the MSFT `.../install/Win10` page are missing something?

**Comment by jamesdavidhoward** [comment]
Some information appears in the Event Log at (roughly) the install / startup time, but it does not seem relevant:
11:40:45pm The access history in hive \??\C:\ProgramData\Microsoft\Windows\AppRepository\Packages\WhitewaterFoundryLtd.Co.FedoraRemixforWSL_31.5.1.0_x64__kd1vv0z0vy70w\ActivationStore.dat was cleared updating 0 keys and creating 0 modified pages.
11:40:47pm  Installation Started: Windows has started installing the following update: 9N6GDM4K2HNC-WhitewaterFoundryLtd.Co.FedoraRemixforWSL
11:40:48pm  Installation Successful: Windows successfully installed the following update: 9N6GDM4K2HNC-WhitewaterFoundryLtd.Co.FedoraRemixforWSL

Also about this time, there were 56 (!) "Audit Success" Event Log entries documenting "Enumerate Credentials" calls to the "Credential Manager".  That seems a bit excessive & redundant.

**Comment by crramirez** [comment]
Hello,

Open powershell in administrator mode and execute :

dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart

Regards,
Carlos

**Comment by crramirez** [comment]
OK I saw that you already enabled it. Double check if the virtualization is enabled in the BIOS

**Comment by jamesdavidhoward** [comment]
Thanks much for the reminder, but I checked in BIOS settings that the Intel chip's VT and VT-D are both enabled.

Can I infer from your current & previous reply that the error code originally quoted refers specifically to the Hyper-V functionality?
— if so, it would be really helpful if the error message said that (instead of a generic message about some anonymous dependency)
— I will proceed investigating based on the assumption that the problem is with Hyper-V or its startup

More news later...

James D. Howard. jhoward@alumni.caltech.edu

________________________________

**Comment by jamesdavidhoward** [comment]
I eventually found the problem:

When Intel hardware virtualization (VT, VT-d) is turned on (or is changed either way, actually), my machine requires a complete COLD power off and restart for the change to be effective.  Otherwise the BIOS setting is remembered, but is NOT actually in effect.

A cold restart has not been done for a very long time, as the machine is a controller for a large NAS store that takes a long time to return to operability if power cycled.  The looks-like-it-worked BIOS setting is a lie.  I do not know if this Intel BIOS (i.e. created for and run on an Intel development machine) is typical in this regard.

If other machines are like this, it might be good to warn somewhere in a FAQ or whatever about this.  I was confused because Oracle's VirtualBox was operating as expected, without complaint - though actually using something like paravirtualization.

Nonetheless, it would be very good if the user-unusable 32-bit error codes like 0x800.... were translated into something helpful.  There IS a database and tool for these codes;  I had seen it in use within Intel, but I've been retired from there for 5 years.
---
James D. Howard   jhoward@alumni.caltech.edu

________________________________________

**Comment by crramirez** [comment]
I agree. This error is generated by WSL directly. Let's see if we can intercept it in the launcher.

Glad it works
