### ISSUE TITLE
I can't use dnf pm. It's destroyed

### ISSUE THREAD

**Issue by amirhosseinaramfar** [WhitewaterFoundry/Fedora-Remix-for-WSL#95]
[amir@amir-fedora ~]$ sudo dnf upgrade
[Errno 21] Is a directory: '/var/cache/dnf/metadata_lock.pid'

**Comment by crramirez** [comment]
Hello,

You can safely delete this :

/var/cache/dnf/metadata_lock.pid

Regards,
Carlos

**Comment by saigkill** [comment]
@amirhosseinaramfar: Hello Amir. Is the issue gone?

**Comment by saigkill** [comment]
Closed by no reaction. Feel free to reopen.
