### ISSUE TITLE
package name wrong

### ISSUE THREAD

**Issue by GSRLW** [WhitewaterFoundry/Fedora-Remix-for-WSL#98]
today , I install  Fedora-Remix-for-WSL-SL_33.1.0.0_x64_arm64 .
 then I found it in my folder "\usr\AppData\Local\Packages"   ,the package folder name is "  d7178e7a-49e4-4897-be1d-af6a19e4c417_zxdhfybd17krt  " , i think it is so difficult to  find it .
this problem just show in  version " Fedora-Remix-for-WSL-SL_32.1.0.0_x64_arm64  "  .
but when I install " 2020-08-06-09-09-37-download-Fedora-Remix-for-WSL_31.5.0.0_x64_arm64 " , I can find my folder with name....
sometimes I use this information to  find " ext4.vhdx " easily . so maybe you can fixed it.

**Comment by crramirez** [comment]
Hello,

I will try to see where it is generated and try to change it.

Regards,
Carlos

**Comment by GSRLW** [comment]
thanks,  you just install it in your PC, and then you can find it.  
the old package "Fedora-Remix-for-WSL_31.5.0.0_x64_arm64" 
 set path 
   ---> 
  "C:\Users\XXXX\AppData\Local\Packages\WhitewaterFoundryLtd.Co.FedoraRemixforWSL_zxdhfybd17krt\LocalState\rootfs"
(if WSL2 ,you find extf4.vdhx in LocalState).

**Comment by crramirez** [comment]
Hello,

We released a new package with this correction

Regards

**Comment by GSRLW** [comment]
ok, let me have a try. thanks . ^_^

**Comment by GSRLW** [comment]
thanks 。
